/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import com.mysql.jdbc.StringUtils;
import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.bean.Cidade;
import model.bean.Estado;
import model.bean.PessoaFisica;
import model.bean.PessoaJuridica;
import model.dao.CidadeDAO;
import model.dao.EstadoDAO;
import model.dao.PessoaDAO;
import model.dao.PessoaFisicaDAO;
import model.dao.PessoaJuridicaDAO;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Lucas Matheus
 */
public class TelaCliente extends javax.swing.JDialog {
    Color vermelho = new Color(246, 91, 92, 255);
    Color verde = new Color(50, 205, 50, 255);
    Color branco = new Color(255, 255, 255, 255);
    private boolean editando = false;
    private Object clienteCarregado;
    TelaPrincipal tp;
    
    public TelaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/logoSistema_16px.png")).getImage());
        txtIM.setVisible(false);
        AutoCompleteDecorator.decorate(cmbEstado);
        AutoCompleteDecorator.decorate(cmbCidade);
        carregarEstado(null); 
        txtDataCadastro.setEditable(false);
        limpaCampos();
    }
    
    public TelaCliente(java.awt.Frame parent, boolean modal, byte tipo, Object cliente) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/logoSistema_16px.png")).getImage());
        this.tp = (TelaPrincipal) parent;
        AutoCompleteDecorator.decorate(cmbEstado);
        AutoCompleteDecorator.decorate(cmbCidade);
        txtDataCadastro.setEditable(false);
            if(tipo==0){ //novo
                txtIM.setVisible(false);
                carregarEstado(null); 
                limpaCampos();
            } else if (tipo==1){ //visualizar
                this.clienteCarregado = cliente;
                habilitaBotoes();
                carregarCliente();
            } else if (tipo==2){ //editando
                this.clienteCarregado = cliente;
                this.editando = true;
                desabilitaBotoes();
                carregarCliente();
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpPessoa = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtNomeERazaoSocial = new javax.swing.JTextField();
        lblNomeERazaoSocial = new javax.swing.JLabel();
        txtApelidoENomeFantasia = new javax.swing.JTextField();
        lblApelidoENomeFantasia = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDataCadastro = new javax.swing.JFormattedTextField();
        lblDataNascimentoEDataAbertura = new javax.swing.JLabel();
        txtCPFECNPJ = new javax.swing.JFormattedTextField();
        lblCPFECPNJ = new javax.swing.JLabel();
        txtRGEIE = new javax.swing.JTextField();
        lblRGEIE = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtIM = new javax.swing.JTextField();
        lblSexoEIM = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        txtTelefoneFixo = new javax.swing.JFormattedTextField();
        txtTelefoneCelular = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDataNascimentoEDataAbertura = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JFormattedTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbCidade = new javax.swing.JComboBox<>();
        chkHabilitado = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        btnPessoaFisica = new javax.swing.JRadioButton();
        btnPessoaJuridica = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltarCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestão de Clientes");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(246, 91, 92));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientes_36px.png"))); // NOI18N
        jLabel1.setText("Gestão de Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(233, 234, 234));

        jPanel3.setBackground(new java.awt.Color(233, 234, 234));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtNomeERazaoSocial.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomeERazaoSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeERazaoSocialKeyTyped(evt);
            }
        });

        lblNomeERazaoSocial.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNomeERazaoSocial.setText("<html>Nome: <body> <span style=\"color: red;\">*</span></body></html>");

        txtApelidoENomeFantasia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtApelidoENomeFantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApelidoENomeFantasiaKeyTyped(evt);
            }
        });

        lblApelidoENomeFantasia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblApelidoENomeFantasia.setText("Apelido:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("<html>Data de Cadastro: <body> <span style=\"color: red;\">*</span></body></html>");

        try {
            txtDataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCadastro.setToolTipText("");
        txtDataCadastro.setFocusable(false);
        txtDataCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDataCadastro.setNextFocusableComponent(txtApelidoENomeFantasia);

        lblDataNascimentoEDataAbertura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDataNascimentoEDataAbertura.setText("<html>Data de Nasc: <body> <span style=\"color: red;\">*</span></body></html>");

        try {
            txtCPFECNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFECNPJ.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCPFECNPJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPFECNPJKeyReleased(evt);
            }
        });

        lblCPFECPNJ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCPFECPNJ.setText("<html>CPF: <body> <span style=\"color: red;\">*</span></body></html>");

        txtRGEIE.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtRGEIE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRGEIEKeyTyped(evt);
            }
        });

        lblRGEIE.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRGEIE.setText("RG:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("E-Mail:");

        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("Tel. Fixo:");

        jPanel5.setBackground(new java.awt.Color(233, 234, 234));
        jPanel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtIM.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIM.setNextFocusableComponent(txtCPFECNPJ);
        txtIM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIMKeyTyped(evt);
            }
        });

        lblSexoEIM.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSexoEIM.setText("<html>Sexo: <body> <span style=\"color: red;\">*</span></body></html>");

        cmbSexo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        cmbSexo.setFocusable(false);
        cmbSexo.setNextFocusableComponent(txtCPFECNPJ);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtIM, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblSexoEIM)
            .addComponent(cmbSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(lblSexoEIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        try {
            txtTelefoneFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneFixo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefoneFixo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefoneFixoKeyReleased(evt);
            }
        });

        try {
            txtTelefoneCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneCelular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefoneCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefoneCelularKeyReleased(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("Tel. Celular:");

        txtDataNascimentoEDataAbertura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApelidoENomeFantasia)
                            .addComponent(txtApelidoENomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNomeERazaoSocial)
                    .addComponent(lblNomeERazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCPFECPNJ)
                            .addComponent(txtCPFECNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRGEIE)
                            .addComponent(txtRGEIE, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDataNascimentoEDataAbertura, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(txtDataNascimentoEDataAbertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(txtTelefoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeERazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDataNascimentoEDataAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeERazaoSocial)
                            .addComponent(txtDataNascimentoEDataAbertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCPFECNPJ)
                                    .addComponent(txtRGEIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCPFECPNJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRGEIE))
                                .addGap(29, 29, 29)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lblApelidoENomeFantasia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtApelidoENomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(11, 11, 11)
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefoneFixo)
                            .addComponent(txtTelefoneCelular))))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(233, 234, 234));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("<html>Logradouro: <body> <span style=\"color: red;\">*</span></body></html>");

        txtLogradouro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLogradouro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLogradouroKeyTyped(evt);
            }
        });

        txtNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("<html>Número: <body> <span style=\"color: red;\">*</span></body></html>");

        txtComplemento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtComplementoKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Complemento:");

        txtBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBairroKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("<html>Bairro: <body> <span style=\"color: red;\">*</span></body></html>");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("<html>CEP: <body> <span style=\"color: red;\">*</span></body></html>");

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.setText("");
        txtCEP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cmbEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbEstado.setToolTipText("");
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("<html>Estado: <body> <span style=\"color: red;\">*</span></body></html>");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("<html>Cidade: <body> <span style=\"color: red;\">*</span></body></html>");

        cmbCidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbCidade.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(439, 439, 439)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbEstado)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCidade))))
        );

        chkHabilitado.setBackground(new java.awt.Color(233, 234, 234));
        chkHabilitado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chkHabilitado.setSelected(true);
        chkHabilitado.setText("Habilitado");
        chkHabilitado.setFocusable(false);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Observações:");

        txtObservacoes.setColumns(20);
        txtObservacoes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtObservacoes.setRows(5);
        txtObservacoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObservacoesKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtObservacoes);

        btnPessoaFisica.setBackground(new java.awt.Color(233, 234, 234));
        grpPessoa.add(btnPessoaFisica);
        btnPessoaFisica.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPessoaFisica.setSelected(true);
        btnPessoaFisica.setText("Pessoa Física");
        btnPessoaFisica.setFocusable(false);
        btnPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoaFisicaActionPerformed(evt);
            }
        });

        btnPessoaJuridica.setBackground(new java.awt.Color(233, 234, 234));
        grpPessoa.add(btnPessoaJuridica);
        btnPessoaJuridica.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPessoaJuridica.setText("Pessoa Jurídica");
        btnPessoaJuridica.setFocusable(false);
        btnPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPessoaJuridicaActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inserir.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setFocusable(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setFocusable(false);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setFocusable(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVoltarCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVoltarCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltar_cancelar.png"))); // NOI18N
        btnVoltarCancelar.setText("Voltar");
        btnVoltarCancelar.setFocusable(false);
        btnVoltarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPessoaFisica)
                        .addGap(18, 18, 18)
                        .addComponent(btnPessoaJuridica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkHabilitado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltarCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHabilitado)
                    .addComponent(btnPessoaFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPessoaJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnVoltarCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(835, 653));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtApelidoENomeFantasiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApelidoENomeFantasiaKeyTyped
        if(btnPessoaFisica.isSelected() && !Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()))
            evt.consume();
        else if (btnPessoaJuridica.isSelected() && !Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !".-&'".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(btnPessoaFisica.isSelected() && txtApelidoENomeFantasia.getText().length()>=20)
            evt.consume();
        else if(btnPessoaJuridica.isSelected() && txtApelidoENomeFantasia.getText().length()>=80)
            evt.consume();
    }//GEN-LAST:event_txtApelidoENomeFantasiaKeyTyped

    private void txtRGEIEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRGEIEKeyTyped
        if(btnPessoaFisica.isSelected() && !Character.isAlphabetic(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar()) && !".-".contains(evt.getKeyChar()+""))
            evt.consume();
        else if (btnPessoaJuridica.isSelected() && !Character.isDigit(evt.getKeyChar()) && !".".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(btnPessoaFisica.isSelected() && txtRGEIE.getText().length()>=20)
            evt.consume();
        else if(btnPessoaJuridica.isSelected() && txtRGEIE.getText().length()>=25)
            evt.consume();
    }//GEN-LAST:event_txtRGEIEKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        if(txtEmail.getText().length()>=70)
            evt.consume();
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtLogradouroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLogradouroKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !".'".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtLogradouro.getText().length()>=70)
            evt.consume();
    }//GEN-LAST:event_txtLogradouroKeyTyped

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
        if(!Character.isDigit(evt.getKeyChar()) && !"-/".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtNumero.getText().length()>=8)
            evt.consume();
    }//GEN-LAST:event_txtNumeroKeyTyped

    private void txtComplementoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !"-/.".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtComplemento.getText().length()>=30)
            evt.consume();
    }//GEN-LAST:event_txtComplementoKeyTyped

    private void txtBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !".'".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtBairro.getText().length()>=30)
            evt.consume();
    }//GEN-LAST:event_txtBairroKeyTyped

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        carregarCidade((Estado) cmbEstado.getSelectedItem());
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void txtCPFECNPJKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFECNPJKeyReleased
        if(txtCPFECNPJ.isEditable()){
            if(btnPessoaFisica.isSelected()){
                if(!validarCPF())
                    txtCPFECNPJ.setBackground(vermelho);
                else txtCPFECNPJ.setBackground(verde);
            } else {
                if(!validarCNPJ())
                    txtCPFECNPJ.setBackground(vermelho);
                else txtCPFECNPJ.setBackground(verde);
            }
        }  else txtCPFECNPJ.setBackground(null);
    }//GEN-LAST:event_txtCPFECNPJKeyReleased

    private void txtNomeERazaoSocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeERazaoSocialKeyTyped
        if(btnPessoaFisica.isSelected() && !Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !"'".contains(evt.getKeyChar()+""))
            evt.consume();
        else if (btnPessoaJuridica.isSelected() && !Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !".-&'".contains(evt.getKeyChar()+""))
            evt.consume();

        if(btnPessoaFisica.isSelected() && txtNomeERazaoSocial.getText().length()>=50)
            evt.consume();
        else if(btnPessoaJuridica.isSelected() && txtNomeERazaoSocial.getText().length()>=80)
            evt.consume();
    }//GEN-LAST:event_txtNomeERazaoSocialKeyTyped

    private void txtIMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIMKeyTyped
        if (!Character.isDigit(evt.getKeyChar()))
            evt.consume();
        
        if(txtIM.getText().length()>=25)
            evt.consume();
    }//GEN-LAST:event_txtIMKeyTyped

    private void btnPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoaFisicaActionPerformed
        controlaPessoa();
    }//GEN-LAST:event_btnPessoaFisicaActionPerformed

    private void btnPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPessoaJuridicaActionPerformed
        controlaPessoa();
    }//GEN-LAST:event_btnPessoaJuridicaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(!(cmbEstado.getSelectedItem()==null) && !(cmbCidade.getSelectedItem()==null) && !StringUtils.isNullOrEmpty(txtNomeERazaoSocial.getText().trim()) && !StringUtils.isNullOrEmpty(txtDataCadastro.getText()) && !txtDataCadastro.getText().equals("  /  /       :  ") && !StringUtils.isNullOrEmpty(txtCPFECNPJ.getText()) && !txtCPFECNPJ.getText().equals("   .   .   -  ") && !StringUtils.isNullOrEmpty(txtLogradouro.getText().trim()) && !StringUtils.isNullOrEmpty(txtNumero.getText().trim()) && !StringUtils.isNullOrEmpty(txtCEP.getText()) && !txtCEP.getText().equals("     -   ") && !StringUtils.isNullOrEmpty(txtBairro.getText().trim())){
            if(btnPessoaFisica.isSelected()){
                if(txtDataNascimentoEDataAbertura.getDate()!=null){
                    if(validarCPF()){
                        PessoaFisica pessoaFisica = new PessoaFisica();
                        if(chkHabilitado.isSelected())
                            pessoaFisica.setIsHabilitado(1);
                        else pessoaFisica.setIsHabilitado(0);
                        pessoaFisica.setNome(txtNomeERazaoSocial.getText().trim());
                        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy"); 
                        pessoaFisica.setDataNascimento(dateFormat.format(txtDataNascimentoEDataAbertura.getDate()));
                        pessoaFisica.setDataCadastro(txtDataCadastro.getText());
                        pessoaFisica.setApelido(txtApelidoENomeFantasia.getText().trim());
                            if(cmbSexo.getSelectedItem().toString().equals("Masculino"))
                                pessoaFisica.setSexo("M");
                            else pessoaFisica.setSexo("F");
                        pessoaFisica.setCpf(txtCPFECNPJ.getText());
                        pessoaFisica.setRg(txtRGEIE.getText().trim());
                        pessoaFisica.setEmail(txtEmail.getText().trim());
                        pessoaFisica.setTelefoneFixo(txtTelefoneFixo.getText());
                        pessoaFisica.setTelefoneCelular(txtTelefoneCelular.getText());
                        pessoaFisica.setLogradouro(txtLogradouro.getText().trim());
                        pessoaFisica.setNumero(txtNumero.getText().trim());
                        pessoaFisica.setCep(txtCEP.getText());
                        pessoaFisica.setComplemento(txtComplemento.getText().trim());
                        pessoaFisica.setBairro(txtBairro.getText().trim());
                        pessoaFisica.setCidade((Cidade) cmbCidade.getSelectedItem());
                        pessoaFisica.setObservacoes(txtObservacoes.getText().trim());
                        PessoaFisicaDAO pessoaFisicaDAO = new PessoaFisicaDAO();
                        habilitaBotoes();
                            if(!this.editando){
                                pessoaFisicaDAO.adicionaPessoaFisica(pessoaFisica);
                                pessoaFisica.setIdPessoaFisica(pessoaFisicaDAO.getLastCodePessoaFisica());
                                PessoaDAO daop = new PessoaDAO();
                                pessoaFisica.setIdPessoa(daop.getLastCodePessoa());
                                tp.clienteTableModel.addRow(pessoaFisica);
                                JOptionPane.showMessageDialog(this, "Registro incluído com sucesso!", "Caixa de Diálogo", 1); 
                                this.dispose();
                            } else {
                                pessoaFisica.setIdPessoa(((PessoaFisica) clienteCarregado).getIdPessoa());
                                pessoaFisica.setIdPessoaFisica(((PessoaFisica) clienteCarregado).getIdPessoaFisica());
                                pessoaFisicaDAO.atualizaPessoaFisica(pessoaFisica);
                                tp.carregarTabelaClientes();
                                this.editando = false;
                                JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!", "Caixa de Diálogo", 1);
                                this.dispose();
                            }
                        this.clienteCarregado = pessoaFisica;
                    } else JOptionPane.showMessageDialog(null, "O CPF digitado não é válido!", "Caixa de Diálogo", 0);
                } else JOptionPane.showMessageDialog(null, "A data de nascimento não foi digitada ou não é válida!", "Caixa de Diálogo", 0);
            } else if (btnPessoaJuridica.isSelected()){
                if(txtDataNascimentoEDataAbertura.getDate()!=null){
                    if(validarCNPJ()){
                        PessoaJuridica pessoaJuridica = new PessoaJuridica();
                        pessoaJuridica.setIsFornecedor(0);
                        if(chkHabilitado.isSelected())
                            pessoaJuridica.setIsHabilitado(1);
                        else pessoaJuridica.setIsHabilitado(0);
                        pessoaJuridica.setRazaoSocial(txtNomeERazaoSocial.getText().trim());
                        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy"); 
                        pessoaJuridica.setDataAbertura(dateFormat.format(txtDataNascimentoEDataAbertura.getDate()));
                        pessoaJuridica.setDataCadastro(txtDataCadastro.getText());
                        pessoaJuridica.setNomeFantasia(txtApelidoENomeFantasia.getText().trim());
                        pessoaJuridica.setIm(txtIM.getText().trim());
                        pessoaJuridica.setCnpj(txtCPFECNPJ.getText());
                        pessoaJuridica.setIe(txtRGEIE.getText().trim());
                        pessoaJuridica.setEmail(txtEmail.getText().trim());
                        pessoaJuridica.setTelefoneFixo(txtTelefoneFixo.getText());
                        pessoaJuridica.setTelefoneCelular(txtTelefoneCelular.getText());
                        pessoaJuridica.setLogradouro(txtLogradouro.getText().trim());
                        pessoaJuridica.setNumero(txtNumero.getText().trim());
                        pessoaJuridica.setCep(txtCEP.getText());
                        pessoaJuridica.setComplemento(txtComplemento.getText().trim());
                        pessoaJuridica.setBairro(txtBairro.getText().trim());
                        pessoaJuridica.setCidade((Cidade) cmbCidade.getSelectedItem());
                        pessoaJuridica.setObservacoes(txtObservacoes.getText().trim());
                        PessoaJuridicaDAO pessoaJuridicaDAO = new PessoaJuridicaDAO();
                        habilitaBotoes();
                            if(!this.editando){
                                pessoaJuridicaDAO.adicionaPessoaJuridica(pessoaJuridica);
                                pessoaJuridica.setIdPessoaJuridica(pessoaJuridicaDAO.getLastCodePessoaJuridica());
                                PessoaDAO daop = new PessoaDAO();
                                pessoaJuridica.setIdPessoa(daop.getLastCodePessoa());
                                tp.clienteTableModel.addRow(pessoaJuridica);
                                JOptionPane.showMessageDialog(this, "Registro incluído com sucesso!", "Caixa de Diálogo", 1); 
                                this.dispose();
                            } else {
                                pessoaJuridica.setIdPessoa(((PessoaJuridica) clienteCarregado).getIdPessoa());
                                pessoaJuridica.setIdPessoaJuridica(((PessoaJuridica) clienteCarregado).getIdPessoaJuridica());
                                pessoaJuridicaDAO.atualizaPessoaJuridica(pessoaJuridica);
                                tp.carregarTabelaClientes();
                                this.editando = false;
                                JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!", "Caixa de Diálogo", 1);
                                this.dispose();
                            }
                        this.clienteCarregado = pessoaJuridica;
                    } else JOptionPane.showMessageDialog(null, "O CNPJ digitado não é válido!", "Caixa de Diálogo", 0);
                } else JOptionPane.showMessageDialog(null, "A data de abertura não foi digitada ou não é válida!", "Caixa de Diálogo", 0);
            }
        } else JOptionPane.showMessageDialog(null, "Há campos obrigatórios que não foram preenchidos!", "Caixa de Diálogo", 0);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.editando = true;
        desabilitaBotoes();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Você quer mesmo excluir este registro?", "Caixa de Confirmação", 0)==0){
            if(btnPessoaFisica.isSelected()){
                PessoaFisicaDAO dao = new PessoaFisicaDAO();
                    if(dao.removePessoaFisica((PessoaFisica) clienteCarregado)){
                        tp.clienteTableModel.removeRow(clienteCarregado);
                        JOptionPane.showMessageDialog(this, "Registro excluído com sucesso!", "Caixa de Diálogo", 1);
                        this.dispose();
                    } else JOptionPane.showMessageDialog(null, "Não foi possível excluir este registro.\nProvavelmente há vendas vinculadas a ele!", "Caixa de Afirmação", 0);
            } else if (btnPessoaJuridica.isSelected()){
                PessoaJuridicaDAO dao = new PessoaJuridicaDAO();
                    if(dao.removePessoaJuridica((PessoaJuridica) clienteCarregado)){
                        tp.clienteTableModel.removeRow(clienteCarregado);
                        JOptionPane.showMessageDialog(this, "Registro excluído com sucesso!", "Caixa de Diálogo", 1);
                        this.dispose();
                    } else JOptionPane.showMessageDialog(null, "Não foi possível excluir este registro.\nProvavelmente há vendas vinculadas a ele!", "Caixa de Afirmação", 0);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCancelarActionPerformed
        if(this.editando){
            if(JOptionPane.showConfirmDialog(this, "Você quer mesmo desfazer as alterações deste registro?", "Caixa de Confirmação", 0)==0){
                habilitaBotoes();
                this.editando = false;
                carregarCliente();
            }   
        } else if(JOptionPane.showConfirmDialog(this, "Você quer mesmo voltar à tela anterior?", "Caixa de Confirmação", 0)==0)
        this.dispose();
    }//GEN-LAST:event_btnVoltarCancelarActionPerformed

    private void txtObservacoesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObservacoesKeyTyped
        if(txtObservacoes.getText().length()>=65535)
            evt.consume();
    }//GEN-LAST:event_txtObservacoesKeyTyped

    private void txtTelefoneFixoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneFixoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneFixoKeyReleased

    private void txtTelefoneCelularKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneCelularKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneCelularKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaCliente dialog = new TelaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JRadioButton btnPessoaFisica;
    private javax.swing.JRadioButton btnPessoaJuridica;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltarCancelar;
    private javax.swing.JCheckBox chkHabilitado;
    private javax.swing.JComboBox<Object> cmbCidade;
    private javax.swing.JComboBox<Object> cmbEstado;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.ButtonGroup grpPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApelidoENomeFantasia;
    private javax.swing.JLabel lblCPFECPNJ;
    private javax.swing.JLabel lblDataNascimentoEDataAbertura;
    private javax.swing.JLabel lblNomeERazaoSocial;
    private javax.swing.JLabel lblRGEIE;
    private javax.swing.JLabel lblSexoEIM;
    private javax.swing.JTextField txtApelidoENomeFantasia;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCPFECNPJ;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtDataCadastro;
    private com.toedter.calendar.JDateChooser txtDataNascimentoEDataAbertura;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIM;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNomeERazaoSocial;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextArea txtObservacoes;
    private javax.swing.JTextField txtRGEIE;
    private javax.swing.JFormattedTextField txtTelefoneCelular;
    private javax.swing.JFormattedTextField txtTelefoneFixo;
    // End of variables declaration//GEN-END:variables
    
    private String definirDataCadastro (){
	DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss"); 
	Date date = new Date(); 
	return dateFormat.format(date); 
    }
    
    private void carregarEstado (Estado est){
        EstadoDAO dao = new EstadoDAO();
            for(Estado estado:dao.getListaEstado()){
                cmbEstado.addItem(estado);
                    if(est==null && estado.toString().equals("SP")){
                        cmbEstado.setSelectedItem(estado);
                        carregarCidade(estado);
                    } else if (est!=null && estado.getIdEstado()==est.getIdEstado())
                        cmbEstado.setSelectedItem(estado);
            }
    }
    
    private void carregarCidade (Estado estado){
        cmbCidade.removeAllItems();
        CidadeDAO dao = new CidadeDAO();
            for(Cidade cidade:dao.getListaCidade(estado)){
                cmbCidade.addItem(cidade);
            }
    }   
    
    private void carregarCidade (Cidade cid){
        cmbCidade.removeAllItems();
        CidadeDAO dao = new CidadeDAO();
            for(Cidade cidade:dao.getListaCidade(cid.getEstado())){
                cmbCidade.addItem(cidade);
                    if(cid!=null && cidade.getIdCidade()==cid.getIdCidade())
                        cmbCidade.setSelectedItem(cidade);
            }
    }   
    
    private boolean validarCPF(){
        if(txtCPFECNPJ.getText().length()!=14)
            return false;
        else {
        int calculo = 0;
            
            for(int i = 0, j=10;i<11;i++)
                    if(i!=3 && i!=7)
                        calculo += ((int) txtCPFECNPJ.getText().charAt(i)-48)*j--;

            calculo = 11-calculo%11;
                if(calculo==10 || calculo==11)
                    calculo = 0;

            if(((int)txtCPFECNPJ.getText().charAt(12)-48)==calculo){
                calculo = 0;
                    for(int i = 0, j=11; i<13; i++)
                        if(i!=3 && i!=7 && i!=11)
                            calculo += ((int) txtCPFECNPJ.getText().charAt(i)-48)*j--;
                calculo = 11-calculo%11;
                    if(calculo==10 || calculo==11)
                        calculo = 0;
                    if(((int)txtCPFECNPJ.getText().charAt(13)-48)==calculo)
                        return true;
                    else return false;
            } else return false;
        }
    }

    private boolean validarCNPJ(){
        if(txtCPFECNPJ.getText().length()!=18)
            return false;
        else {
        int calculo = 0;

            for(int i=14, j=2;i>=0;i--)
                if(i!=2 && i!=6 && i!=10){
                    if(j==10)
                        j = 2;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                    calculo += ((int) txtCPFECNPJ.getText().charAt(i)-48)*j++;
                }
            calculo = (calculo%11);
                if(calculo<2)
                    calculo = 0;
                else calculo = 11-calculo;
            if(calculo==((int) txtCPFECNPJ.getText().charAt(16)-48)){
                calculo = 0;
                for(int i=16, j=2;i>=0;i--)
                    if(i!=2 && i!=6 && i!=10 && i!=15){
                        if(j==10)
                            j = 2;
                        calculo += ((int) txtCPFECNPJ.getText().charAt(i)-48)*j++;
                    }
                calculo = (calculo%11);
                    if(calculo<2)
                        calculo = 0;
                    else calculo = 11-calculo;
                if(calculo==((int) txtCPFECNPJ.getText().charAt(17)-48))
                    return true;
                else return false;
            } else return false;
        }
    }
    
    private void habilitaBotoes(){
        desabilitaCampos();
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }
    
    private void desabilitaBotoes(){
        habilitaCampos();
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
            if(!this.editando){
                btnPessoaFisica.setEnabled(true);
                btnPessoaJuridica.setEnabled(true);
            } else {
                btnPessoaFisica.setEnabled(false);
                btnPessoaJuridica.setEnabled(false);
            }
    }
    
    private void desabilitaCampos(){
        btnPessoaFisica.setEnabled(false);
        btnPessoaJuridica.setEnabled(false);
        chkHabilitado.setEnabled(false);
        txtNomeERazaoSocial.setEditable(false);
        txtDataNascimentoEDataAbertura.setEnabled(false);
        txtApelidoENomeFantasia.setEditable(false);
        cmbSexo.setEnabled(false);
        txtIM.setEditable(false);
        txtCPFECNPJ.setEditable(false);
        txtCPFECNPJ.setBackground(null);
        txtRGEIE.setEditable(false);
        txtEmail.setEditable(false);
        txtTelefoneFixo.setEditable(false);
        txtTelefoneCelular.setEditable(false);
        txtLogradouro.setEditable(false);
        txtNumero.setEditable(false);
        txtCEP.setEditable(false);
        txtComplemento.setEditable(false);
        txtBairro.setEditable(false);
        cmbEstado.setEnabled(false);
        cmbCidade.setEnabled(false);
        txtObservacoes.setEditable(false);
        txtObservacoes.setBackground(null);
    }
    
    private void habilitaCampos(){
        chkHabilitado.setEnabled(true);
        txtNomeERazaoSocial.setEditable(true);
        txtDataNascimentoEDataAbertura.setEnabled(true);
        txtApelidoENomeFantasia.setEditable(true);
        cmbSexo.setEnabled(true);
        txtIM.setEditable(true);
        txtCPFECNPJ.setEditable(true);
        txtCPFECNPJ.setBackground(branco);
        txtRGEIE.setEditable(true);
        txtEmail.setEditable(true);
        txtTelefoneFixo.setEditable(true);
        txtTelefoneCelular.setEditable(true);
        txtLogradouro.setEditable(true);
        txtNumero.setEditable(true);
        txtCEP.setEditable(true);
        txtComplemento.setEditable(true);
        txtBairro.setEditable(true);
        cmbEstado.setEnabled(true);
        cmbCidade.setEnabled(true);
        txtObservacoes.setEditable(true);
        txtObservacoes.setBackground(branco);
        txtNomeERazaoSocial.requestFocus();
    }
    
    private void controlaPessoa(){
        if(btnPessoaFisica.isSelected()){
            lblNomeERazaoSocial.setText("<html>Nome: <body> <span style=\"color: red;\">*</span></body></html>");
                if(txtNomeERazaoSocial.getText().length()>50)
                    txtNomeERazaoSocial.setText(txtNomeERazaoSocial.getText().substring(0, 50));
            lblDataNascimentoEDataAbertura.setText("<html>Data de Nasc: <body> <span style=\"color: red;\">*</span></body></html>");
            lblApelidoENomeFantasia.setText("Apelido:");
                if(txtApelidoENomeFantasia.getText().length()>20)
                    txtApelidoENomeFantasia.setText(txtApelidoENomeFantasia.getText().substring(0, 20));
            lblSexoEIM.setText("<html>Sexo: <body> <span style=\"color: red;\">*</span></body></html>");
            txtIM.setVisible(false);
            cmbSexo.setVisible(true);
            txtApelidoENomeFantasia.setNextFocusableComponent(cmbSexo);
            lblCPFECPNJ.setText("<html>CPF: <body> <span style=\"color: red;\">*</span></body></html>");
            txtCPFECNPJ.setValue(null);
                if(btnPessoaFisica.isEnabled() && btnPessoaJuridica.isEnabled())
                    txtCPFECNPJ.setBackground(branco);
            try {
                txtCPFECNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
            } catch (ParseException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            lblRGEIE.setText("RG:");
                if(txtRGEIE.getText().length()>20)
                    txtRGEIE.setText(txtRGEIE.getText().substring(0, 20));
        } else {
            lblNomeERazaoSocial.setText("<html>Razão Social: <body> <span style=\"color: red;\">*</span></body></html>");
            lblDataNascimentoEDataAbertura.setText("<html>Data de Abertura: <body> <span style=\"color: red;\">*</span></body></html>");
            lblApelidoENomeFantasia.setText("Nome Fantasia:");
            lblSexoEIM.setText("IM:");
            txtIM.setVisible(true);
            cmbSexo.setVisible(false);
            txtApelidoENomeFantasia.setNextFocusableComponent(txtIM);
            lblCPFECPNJ.setText("<html>CNPJ: <body> <span style=\"color: red;\">*</span></body></html>");
            txtCPFECNPJ.setValue(null);
                if(btnPessoaFisica.isEnabled() && btnPessoaJuridica.isEnabled())
                    txtCPFECNPJ.setBackground(branco);
            try {
                txtCPFECNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
            } catch (ParseException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            lblRGEIE.setText("IE:");
        }
    }
    
    private void limpaCampos(){
        desabilitaBotoes();
        btnPessoaFisica.setEnabled(true);
        btnPessoaJuridica.setEnabled(true);
        chkHabilitado.setSelected(true);
        txtNomeERazaoSocial.setText(null);
        txtDataNascimentoEDataAbertura.setDate(null);
        txtDataCadastro.setText(definirDataCadastro());
        txtApelidoENomeFantasia.setText(null);
        cmbSexo.setSelectedIndex(0);
        txtIM.setText(null);
        txtCPFECNPJ.setValue(null);
        txtCPFECNPJ.setBackground(branco);
        txtRGEIE.setText(null);
        txtEmail.setText(null);
        txtTelefoneFixo.setValue(null);
        txtTelefoneCelular.setValue(null);
        txtLogradouro.setText(null);
        txtNumero.setText(null);
        txtCEP.setValue(null);
        txtComplemento.setText(null);
        txtBairro.setText(null);
        cmbEstado.setSelectedIndex(25);
        txtObservacoes.setText(null);
    }
    
    private void carregarCliente(){
        if(clienteCarregado instanceof PessoaFisica){
            btnPessoaFisica.setSelected(true);
            controlaPessoa();
                if(((PessoaFisica) clienteCarregado).getIsHabilitado()==1)    
                    chkHabilitado.setSelected(true);
                else chkHabilitado.setSelected(false);
            txtNomeERazaoSocial.setText(((PessoaFisica) clienteCarregado).getNome());
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            try {
                txtDataNascimentoEDataAbertura.setDate(dateFormat.parse(((PessoaFisica) clienteCarregado).getDataNascimento()));
            } catch (ParseException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtDataCadastro.setText(((PessoaFisica) clienteCarregado).getDataCadastro());
            txtApelidoENomeFantasia.setText(((PessoaFisica) clienteCarregado).getApelido());
            txtCPFECNPJ.setText(((PessoaFisica) clienteCarregado).getCpf());
            txtRGEIE.setText(((PessoaFisica) clienteCarregado).getRg());
            txtEmail.setText(((PessoaFisica) clienteCarregado).getEmail());
                if(((PessoaFisica) clienteCarregado).getTelefoneFixo()!=null && !((PessoaFisica) clienteCarregado).getTelefoneFixo().equals("(  )     -"))
                    txtTelefoneFixo.setText(((PessoaFisica) clienteCarregado).getTelefoneFixo());

                if(((PessoaFisica) clienteCarregado).getTelefoneCelular()!=null && !((PessoaFisica) clienteCarregado).getTelefoneCelular().equals("(  )      -"))
                    txtTelefoneCelular.setText(((PessoaFisica) clienteCarregado).getTelefoneCelular());
            txtLogradouro.setText(((PessoaFisica) clienteCarregado).getLogradouro());
            txtNumero.setText(((PessoaFisica) clienteCarregado).getNumero());
            txtCEP.setText(((PessoaFisica) clienteCarregado).getCep());
            txtComplemento.setText(((PessoaFisica) clienteCarregado).getComplemento());
            txtBairro.setText(((PessoaFisica) clienteCarregado).getBairro());
            carregarEstado(((PessoaFisica) clienteCarregado).getCidade().getEstado());
            carregarCidade(((PessoaFisica) clienteCarregado).getCidade());
            txtObservacoes.setText(((PessoaFisica) clienteCarregado).getObservacoes());
        } else if (clienteCarregado instanceof PessoaJuridica){
            btnPessoaJuridica.setSelected(true);
            controlaPessoa();
                if(((PessoaJuridica) clienteCarregado).getIsHabilitado()==1)    
                    chkHabilitado.setSelected(true);
                else chkHabilitado.setSelected(false);
            txtNomeERazaoSocial.setText(((PessoaJuridica) clienteCarregado).getRazaoSocial());
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            try {
                txtDataNascimentoEDataAbertura.setDate(dateFormat.parse(((PessoaJuridica) clienteCarregado).getDataAbertura()));
            } catch (ParseException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtDataCadastro.setText(((PessoaJuridica) clienteCarregado).getDataCadastro());
            txtApelidoENomeFantasia.setText(((PessoaJuridica) clienteCarregado).getNomeFantasia());
            txtIM.setText(((PessoaJuridica) clienteCarregado).getIm());
            txtCPFECNPJ.setText(((PessoaJuridica) clienteCarregado).getCnpj());
            txtRGEIE.setText(((PessoaJuridica) clienteCarregado).getIe());
            txtEmail.setText(((PessoaJuridica) clienteCarregado).getEmail());
                if(((PessoaJuridica) clienteCarregado).getTelefoneFixo()!=null && !((PessoaJuridica) clienteCarregado).getTelefoneFixo().equals("(  )     -"))
                    txtTelefoneFixo.setText(((PessoaJuridica) clienteCarregado).getTelefoneFixo());

                if(((PessoaJuridica) clienteCarregado).getTelefoneCelular()!=null && !((PessoaJuridica) clienteCarregado).getTelefoneCelular().equals("(  )      -"))
                    txtTelefoneCelular.setText(((PessoaJuridica) clienteCarregado).getTelefoneCelular());
            txtLogradouro.setText(((PessoaJuridica) clienteCarregado).getLogradouro());
            txtNumero.setText(((PessoaJuridica) clienteCarregado).getNumero());
            txtCEP.setText(((PessoaJuridica) clienteCarregado).getCep());
            txtComplemento.setText(((PessoaJuridica) clienteCarregado).getComplemento());
            txtBairro.setText(((PessoaJuridica) clienteCarregado).getBairro());
            carregarEstado(((PessoaJuridica) clienteCarregado).getCidade().getEstado());
            carregarCidade(((PessoaJuridica) clienteCarregado).getCidade());
            txtObservacoes.setText(((PessoaJuridica) clienteCarregado).getObservacoes());
        }
    }
}
