/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import com.mysql.jdbc.StringUtils;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.bean.Compra;
import model.bean.ItemComprado;
import model.bean.Produto;
import model.bean.Sessao;
import model.dao.CompraDAO;
import model.dao.ItemCompradoDAO;
import model.table.ItemCompradoTableModel;
import others.JNumberFormatField;
import others.LeituraDOM;

/**
 *
 * @author LUCASMATHEUSDASILVA
 */
public class TelaCompra extends javax.swing.JFrame {

    /**
     * Creates new form TelaVenda
     */
    Color vermelho = new Color(246, 91, 92, 255);
    Color verde = new Color(50, 205, 50, 255);
    private Compra compraCarregada;
    private final ItemCompradoTableModel itemCompradoTableModel = new ItemCompradoTableModel();
    private String path;
    TelaPrincipal tp;
    
    public TelaCompra() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/logoSistema_16px.png")).getImage());
        tblItensVendidos.setModel(itemCompradoTableModel);
        txtNumero.setEditable(false);
        txtDataCompra.setEditable(false);
        txtRazaoSocial.setEditable(false);
        txtCNPJ.setEditable(false);
        txtIE.setEditable(false);
        txtChaveAcesso.setEditable(false);
        txtPrecoTotalCompra.setEditable(false);
        txtLucro.setEnabled(false);
        btnAplicarEmTodos.setEnabled(false);
        limpaCampos();
    }
    
    public TelaCompra (java.awt.Frame parent, byte tipo, Compra compra){
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/logoSistema_16px.png")).getImage());
        this.tp = (TelaPrincipal) parent;
        tblItensVendidos.setModel(itemCompradoTableModel);
        txtNumero.setEditable(false);
        txtDataCompra.setEditable(false);
        txtRazaoSocial.setEditable(false);
        txtCNPJ.setEditable(false);
        txtIE.setEditable(false);
        txtChaveAcesso.setEditable(false);
        txtPrecoTotalCompra.setEditable(false);
        txtLucro.setEnabled(false);
        btnAplicarEmTodos.setEnabled(false);
        txtNomeUsuario.setText(Sessao.getInstance().getUsuario().getNome().toUpperCase());
        txtNomeEmpresa.setText(Sessao.getInstance().getUsuario().getEmpresa().getRazaoSocial().toUpperCase());
        Locale locale = new Locale("pt","BR");
        GregorianCalendar calendar = new GregorianCalendar(); 
        SimpleDateFormat formatador = new SimpleDateFormat("dd' de 'MMMMM' de 'yyyy",locale);
        txtData.setText(formatador.format(calendar.getTime()));
        txtUltimoAcesso.setText("Último Acesso: " + Sessao.getInstance().getUsuario().getDataUltimoAcesso());
            if(tipo==0){ //novo
                limpaCampos();
            } else if (tipo==1){ //visualizar
                this.compraCarregada = compra;
                carregarCompra();
                habilitaBotoes();
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTituloVendas = new javax.swing.JPanel();
        lblTituloVendas = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        txtDataCompra = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtRazaoSocial = new javax.swing.JTextField();
        txtCNPJ = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblItensVendidos = new javax.swing.JTable();
        lblProduto = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtPrecoTotalCompra = new JNumberFormatField();
        jLabel32 = new javax.swing.JLabel();
        lblItensDeCompra = new javax.swing.JLabel();
        btnImportarXML = new javax.swing.JButton();
        txtChaveAcesso = new javax.swing.JTextField();
        txtLucro = new javax.swing.JSpinner();
        lblPrecoCusto2 = new javax.swing.JLabel();
        lblPrecoCusto1 = new javax.swing.JLabel();
        btnAplicarEmTodos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtData = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JLabel();
        txtUltimoAcesso = new javax.swing.JLabel();
        btnVoltarCancelar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestão de Compras");
        setMinimumSize(new java.awt.Dimension(1040, 706));

        pnlTituloVendas.setBackground(new java.awt.Color(246, 91, 92));

        lblTituloVendas.setBackground(new java.awt.Color(246, 91, 92));
        lblTituloVendas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTituloVendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compra_36px.png"))); // NOI18N
        lblTituloVendas.setText("Gestão de Compras");

        javax.swing.GroupLayout pnlTituloVendasLayout = new javax.swing.GroupLayout(pnlTituloVendas);
        pnlTituloVendas.setLayout(pnlTituloVendasLayout);
        pnlTituloVendasLayout.setHorizontalGroup(
            pnlTituloVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTituloVendasLayout.setVerticalGroup(
            pnlTituloVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloVendas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(233, 234, 234));

        jPanel19.setBackground(new java.awt.Color(233, 234, 234));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações da Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        try {
            txtDataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCompra.setToolTipText("");
        txtDataCompra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("<html>Data de Compra: <body> <span style=\"color: red;\">*</span></body></html>");

        lblCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCliente.setText("<html>Razão Social: <body> <span style=\"color: red;\">*</span></body></html>");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("<html>Número: <body> <span style=\"color: red;\">*</span></body></html>");

        txtNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtRazaoSocial.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCNPJ.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("<html>CNPJ: <body> <span style=\"color: red;\">*</span></body></html>");

        txtIE.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("IE:");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(txtNumero))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDataCompra)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtRazaoSocial))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtIE, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataCompra)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jPanel20.setBackground(new java.awt.Color(233, 234, 234));
        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens da Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        tblItensVendidos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblItensVendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblItensVendidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItensVendidosMouseClicked(evt);
            }
        });
        tblItensVendidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblItensVendidosKeyReleased(evt);
            }
        });
        jScrollPane6.setViewportView(tblItensVendidos);

        lblProduto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblProduto.setText("<html>Chave de Acesso: <body> <span style=\"color: red;\">*</span></body></html>");

        jLabel31.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel31.setText("PREÇO TOTAL:");

        txtPrecoTotalCompra.setBackground(new java.awt.Color(233, 234, 234));
        txtPrecoTotalCompra.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtPrecoTotalCompra.setForeground(new java.awt.Color(66, 180, 73));
        txtPrecoTotalCompra.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPrecoTotalCompra.setText("R$ 0,00");
        txtPrecoTotalCompra.setBorder(null);

        jLabel32.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel32.setText("ITENS DE COMPRA:");

        lblItensDeCompra.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblItensDeCompra.setForeground(new java.awt.Color(66, 180, 73));
        lblItensDeCompra.setText("0");

        btnImportarXML.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnImportarXML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/importar_18px.png"))); // NOI18N
        btnImportarXML.setText("Importar XML");
        btnImportarXML.setFocusable(false);
        btnImportarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarXMLActionPerformed(evt);
            }
        });

        txtChaveAcesso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtLucro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLucro.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(999.99f), Float.valueOf(1.0f)));
        txtLucro.setToolTipText("");
        txtLucro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtLucroStateChanged(evt);
            }
        });

        lblPrecoCusto2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrecoCusto2.setText("%");

        lblPrecoCusto1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrecoCusto1.setText("<html>Lucro: <body> <span style=\"color: red;\">*</span></body></html>");

        btnAplicarEmTodos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAplicarEmTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tudo_18px.png"))); // NOI18N
        btnAplicarEmTodos.setText("Aplicar em Todos");
        btnAplicarEmTodos.setFocusable(false);
        btnAplicarEmTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarEmTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addComponent(txtChaveAcesso)
                                .addGap(18, 18, 18)
                                .addComponent(btnImportarXML)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addComponent(txtLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrecoCusto2))
                            .addComponent(lblPrecoCusto1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAplicarEmTodos))
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecoTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblItensDeCompra)))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addComponent(lblProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtChaveAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnAplicarEmTodos, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(lblPrecoCusto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecoCusto2)
                            .addComponent(btnImportarXML))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecoTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(lblItensDeCompra)))
        );

        jPanel2.setBackground(new java.awt.Color(52, 179, 160));

        txtData.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendario_18px.png"))); // NOI18N
        txtData.setText("XX de XX de XXXX");
        txtData.setFocusable(false);
        txtData.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtNomeUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNomeUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario_18px_1.png"))); // NOI18N
        txtNomeUsuario.setText("XXXXX");
        txtNomeUsuario.setFocusable(false);

        txtNomeEmpresa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNomeEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/empresa_18px.png"))); // NOI18N
        txtNomeEmpresa.setText("XXXXX");
        txtNomeEmpresa.setFocusable(false);

        txtUltimoAcesso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtUltimoAcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ultimoAcesso_18px.png"))); // NOI18N
        txtUltimoAcesso.setText("Último Acesso: XX/XX/XXXX XX:XX");
        txtUltimoAcesso.setFocusable(false);
        txtUltimoAcesso.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(txtNomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUltimoAcesso, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtData, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeUsuario)
                    .addComponent(txtData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeEmpresa)
                    .addComponent(txtUltimoAcesso))
                .addContainerGap())
        );

        btnVoltarCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVoltarCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltar_cancelar.png"))); // NOI18N
        btnVoltarCancelar.setText("Voltar");
        btnVoltarCancelar.setFocusable(false);
        btnVoltarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCancelarActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setFocusable(false);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inserir.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setFocusable(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltarCancelar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltarCancelar)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTituloVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTituloVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1040, 706));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblItensVendidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItensVendidosMouseClicked
        if(tblItensVendidos.getSelectedRow()!=-1){
            ItemComprado selecionado = (ItemComprado) itemCompradoTableModel.getRow(tblItensVendidos.getSelectedRow());
            float lucro = (selecionado.getProduto().getPrecoVenda()/selecionado.getPrecoCompra()-1)*100;
            txtLucro.setValue((float) lucro);
        }
    }//GEN-LAST:event_tblItensVendidosMouseClicked

    private void btnVoltarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCancelarActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Você quer mesmo voltar à tela anterior?", "Caixa de Confirmação", 0)==0)
            this.dispose();
    }//GEN-LAST:event_btnVoltarCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(!StringUtils.isNullOrEmpty(txtDataCompra.getText()) && txtDataCompra.getText()!="  /  /       :  " && !StringUtils.isNullOrEmpty(txtRazaoSocial.getText()) && !StringUtils.isNullOrEmpty(txtCNPJ.getText()) && txtCNPJ.getText()!="  .   .   /    -  " && !StringUtils.isNullOrEmpty(txtIE.getText()) && !StringUtils.isNullOrEmpty(txtChaveAcesso.getText())){
            if(itemCompradoTableModel.getRowCount()!=0){
                if(validarCNPJ()){                    
                    this.compraCarregada.setUsuario(Sessao.getInstance().getUsuario());
                    this.compraCarregada.setItensComprados(itemCompradoTableModel.getList());
                    finalizarCompra();
                } else JOptionPane.showMessageDialog(null, "Não foi possível importar este XML.\nO CNPJ do fornecedor é inválido!", "Caixa de Diálogo", 0);
            } else JOptionPane.showMessageDialog(null, "Não há nenhum item de compra!", "Caixa de Diálogo", 0);
        } else JOptionPane.showMessageDialog(null, "Há campos obrigatórios que não foram preenchidos!", "Caixa de Diálogo", 0);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void tblItensVendidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblItensVendidosKeyReleased
        if(evt.getKeyChar()==evt.VK_ENTER || evt.getKeyCode()==9 || evt.getKeyCode()==38 || evt.getKeyCode()==40){ //ENTER, TAB, CIMA, BAIXO
            if(tblItensVendidos.getSelectedRow()!=-1){
                ItemComprado selecionado = (ItemComprado) itemCompradoTableModel.getRow(tblItensVendidos.getSelectedRow());
                float lucro = (selecionado.getProduto().getPrecoVenda()/selecionado.getPrecoCompra()-1)*100;
                txtLucro.setValue((float) lucro);
            }
        }
    }//GEN-LAST:event_tblItensVendidosKeyReleased

    private void btnImportarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarXMLActionPerformed
        getPath();
        if(this.path!=null){
            limpaCampos();
            txtLucro.setEnabled(true);
            btnAplicarEmTodos.setEnabled(true);
            this.compraCarregada = new Compra();
            LeituraDOM lerXML = new LeituraDOM();
            //Passa para a funcao a primeira tag referente ao objeto (A partir dai, as outras informacoes sao recuperadas recursivamente)
            this.compraCarregada = lerXML.getInfNota(path, "infNFe");
            this.compraCarregada.setFornecedor(lerXML.getInfForn(path, "emit"));
            this.compraCarregada.getFornecedor().setIsFornecedor(1);
            this.compraCarregada.getFornecedor().setIsHabilitado(1);
            int qtd = 0;
            List<ItemComprado> lista = new ArrayList<>();
            for(Produto produto:lerXML.getInfProd(path, "prod")){
                    ItemComprado itemComprado = new ItemComprado();
                    itemComprado.setProduto(produto);
                    itemComprado.setPrecoCompra(produto.getPrecoCompra());
                    itemComprado.setQtdComprada(produto.getQtdDisponivel());
                    lista.add(itemComprado);
                    itemCompradoTableModel.addRow(itemComprado);
                    qtd += itemComprado.getQtdComprada();
                }
            lblItensDeCompra.setText(Integer.toString(qtd));
            
            carregarCompra();
            
            if(validarCNPJ())
                txtCNPJ.setBackground(verde);
            else txtCNPJ.setBackground(vermelho);
        }
    }//GEN-LAST:event_btnImportarXMLActionPerformed

    private void txtLucroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtLucroStateChanged
        if(tblItensVendidos.getSelectedRow()!=-1){
            ItemComprado selecionado = (ItemComprado) itemCompradoTableModel.getRow(tblItensVendidos.getSelectedRow());
            selecionado.getProduto().setPrecoVenda(selecionado.getPrecoCompra()+selecionado.getPrecoCompra()*((float) txtLucro.getValue())/100);
            itemCompradoTableModel.updateRow(tblItensVendidos.getSelectedRow(), selecionado);
        }
    }//GEN-LAST:event_txtLucroStateChanged

    private void btnAplicarEmTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarEmTodosActionPerformed
        if(tblItensVendidos.getRowCount()!=0){
            for(int i=0;i<tblItensVendidos.getRowCount();i++){
                ItemComprado selecionado = (ItemComprado) itemCompradoTableModel.getRow(i);
                selecionado.getProduto().setPrecoVenda(selecionado.getPrecoCompra()+selecionado.getPrecoCompra()*((float) txtLucro.getValue())/100);
                itemCompradoTableModel.updateRow(i, selecionado);
            }
        }
    }//GEN-LAST:event_btnAplicarEmTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarEmTodos;
    private javax.swing.JButton btnImportarXML;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltarCancelar;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblItensDeCompra;
    private javax.swing.JLabel lblPrecoCusto1;
    private javax.swing.JLabel lblPrecoCusto2;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblTituloVendas;
    private javax.swing.JPanel pnlTituloVendas;
    private javax.swing.JTable tblItensVendidos;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JTextField txtChaveAcesso;
    private javax.swing.JLabel txtData;
    private javax.swing.JFormattedTextField txtDataCompra;
    private javax.swing.JTextField txtIE;
    private javax.swing.JSpinner txtLucro;
    private javax.swing.JLabel txtNomeEmpresa;
    private javax.swing.JLabel txtNomeUsuario;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrecoTotalCompra;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JLabel txtUltimoAcesso;
    // End of variables declaration//GEN-END:variables

    private String definirDataVenda (){
	DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss"); 
	Date date = new Date(); 
	return dateFormat.format(date); 
    }
    
    private void habilitaBotoes(){
        desabilitaCampos();
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
    }
    
    private void desabilitaBotoes(){
        habilitaCampos();
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnImportarXML.setEnabled(true);
    }
    
    private void desabilitaCampos(){
        lblProduto.setEnabled(false);
        tblItensVendidos.setEnabled(false);
    }
    
    private void habilitaCampos(){
        txtLucro.setEnabled(false);
        btnAplicarEmTodos.setEnabled(false);
    }

    private void limpaCampos(){
        desabilitaBotoes();
        CompraDAO dao = new CompraDAO();
        txtNumero.setText(Integer.toString(dao.getLastCodeCompra()+1));
        txtDataCompra.setText(null);
        txtRazaoSocial.setText(null);
        txtCNPJ.setText(null);
            if(txtCNPJ.getBackground()==verde || txtCNPJ.getBackground()==vermelho)
                txtCNPJ.setBackground(null);
        txtIE.setText(null);
        txtChaveAcesso.setText(null);
        txtPrecoTotalCompra.setText(null);
        lblItensDeCompra.setText("0");
        txtLucro.setValue((float) 0);
        itemCompradoTableModel.clearRows();
    }
    
    private void carregarCompra(){
        txtDataCompra.setText(this.compraCarregada.getDataCompra());
        txtRazaoSocial.setText(this.compraCarregada.getFornecedor().getRazaoSocial());
        txtCNPJ.setText(this.compraCarregada.getFornecedor().getCnpj());
        txtIE.setText(this.compraCarregada.getFornecedor().getIe());
        txtChaveAcesso.setText(this.compraCarregada.getChaveAcesso());
        txtPrecoTotalCompra.setText(String.format("%.2f", this.compraCarregada.getPrecoTotal()));
            if(StringUtils.isNullOrEmpty(txtNumero.getText())){
                btnImportarXML.setEnabled(false);
                txtNumero.setText(Integer.toString(this.compraCarregada.getIdCompra()));

                ItemCompradoDAO dao = new ItemCompradoDAO();
                this.compraCarregada.setItensComprados(dao.getListaItemComprado(this.compraCarregada));

                int qtd = 0;
                for(ItemComprado itemComprado:compraCarregada.getItensComprados()){
                        itemCompradoTableModel.addRow(itemComprado); 
                        qtd += itemComprado.getQtdComprada();
                    }

                lblItensDeCompra.setText(Integer.toString(qtd));
            }
    }

    private boolean validarCNPJ(){
        if(txtCNPJ.getText().length()!=18)
            return false;
        else {
        int calculo = 0;

            for(int i=14, j=2;i>=0;i--)
                if(i!=2 && i!=6 && i!=10){
                    if(j==10)
                        j = 2;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                    calculo += ((int) txtCNPJ.getText().charAt(i)-48)*j++;
                }
            calculo = (calculo%11);
                if(calculo<2)
                    calculo = 0;
                else calculo = 11-calculo;
            if(calculo==((int) txtCNPJ.getText().charAt(16)-48)){
                calculo = 0;
                for(int i=16, j=2;i>=0;i--)
                    if(i!=2 && i!=6 && i!=10 && i!=15){
                        if(j==10)
                            j = 2;
                        calculo += ((int) txtCNPJ.getText().charAt(i)-48)*j++;
                    }
                calculo = (calculo%11);
                    if(calculo<2)
                        calculo = 0;
                    else calculo = 11-calculo;
                if(calculo==((int) txtCNPJ.getText().charAt(17)-48))
                    return true;
                else return false;
            } else return false;
        }
    }
    
    private void finalizarCompra(){
        CompraDAO dao = new CompraDAO();
        if(dao.adicionaCompra(this.compraCarregada)){
            this.compraCarregada.setIdCompra(dao.getLastCodeCompra());
            tp.compraTableModel.addRow(this.compraCarregada);
            tp.carregarTabelaFornecedores();
            tp.carregarTabelaProdutos();

            JOptionPane.showMessageDialog(this, "Registro incluído com sucesso!", "Caixa de Diálogo", 1);
                if(JOptionPane.showConfirmDialog(this, "Você quer iniciar uma nova compra?", "Caixa de Confirmação", 0)==0){
                    limpaCampos();
                } else this.dispose();
        }
    }
    
    private void getPath(){
        JFileChooser choose = new JFileChooser();
        //Define o titulo da tela de escolhas
        choose.setDialogTitle("Selecione o Arquivo XML");
        //Define um filtro para fazer leitura apenas de arquivos XML
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Arquivo XML (.xml)", "xml");
        choose.setFileFilter(filtro);

        int opc = choose.showSaveDialog(null);

        if(opc == JFileChooser.APPROVE_OPTION)
            path = choose.getSelectedFile().getAbsolutePath();
        else path = null;
    }
}
