/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import com.mysql.jdbc.StringUtils;
import java.awt.Color;
import java.awt.Cursor;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.bean.Grupo;
import model.bean.Marca;
import others.Preco;
import model.bean.Produto;
import model.bean.Subgrupo;
import model.bean.UnidadeMedida;
import model.dao.GrupoDAO;
import model.dao.MarcaDAO;
import model.dao.ProdutoDAO;
import model.dao.SubgrupoDAO;
import model.dao.UnidadeMedidaDAO;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import others.JNumberFormatField;

/**
 *
 * @author Matheus Baptista
 */
public class TelaProduto extends javax.swing.JDialog {

    Color branco = new Color(255, 255, 255, 255);
    private boolean editando = false;
    private Produto produtoCarregado;
    TelaPrincipal tp;
    
    public TelaProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/logoSistema_16px.png")).getImage());
        AutoCompleteDecorator.decorate(cmbMarca);
        AutoCompleteDecorator.decorate(cmbUnidadeMedida);
        AutoCompleteDecorator.decorate(cmbGrupo);
        AutoCompleteDecorator.decorate(cmbSubgrupo);
        carregarUnidadeMedida(null);
        carregarGrupo(null);
        carregaMarca(null);
        txtDataCadastro.setEditable(false);
        limpaCampos();
    }
    
    public TelaProduto(java.awt.Frame parent, boolean modal, byte tipo, Produto produto) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/logoSistema_16px.png")).getImage());
        this.tp = (TelaPrincipal) parent;
        AutoCompleteDecorator.decorate(cmbMarca);
        AutoCompleteDecorator.decorate(cmbUnidadeMedida);
        AutoCompleteDecorator.decorate(cmbGrupo);
        AutoCompleteDecorator.decorate(cmbSubgrupo);
        txtDataCadastro.setEditable(false);
            if(tipo==0){ //novo
                carregarUnidadeMedida(null);
                carregarGrupo(null);
                carregaMarca(null);
                limpaCampos();
            } else if (tipo==1){ //visualizar
                this.produtoCarregado = produto;
                habilitaBotoes();
                carregarProduto();
            } else if (tipo==2){ //editando
                this.produtoCarregado = produto;
                this.editando = true;
                desabilitaBotoes();
                carregarProduto();
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlItens = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtQtdDisponivel = new javax.swing.JTextField();
        lblQtdAtual = new javax.swing.JLabel();
        txtQtdMinima = new javax.swing.JTextField();
        lblQtdMin = new javax.swing.JLabel();
        txtPrecoCusto = new JNumberFormatField();
        lblPrecoCusto = new javax.swing.JLabel();
        txtPrecoVenda = new JNumberFormatField();
        lblPrecoVenda = new javax.swing.JLabel();
        txtDimensoes = new javax.swing.JTextField();
        lblDimensoes = new javax.swing.JLabel();
        txtLocalizacao = new javax.swing.JTextField();
        lblLocalizacao = new javax.swing.JLabel();
        cmbUnidadeMedida = new javax.swing.JComboBox<>();
        lblUnidadeMedida = new javax.swing.JLabel();
        cmbMarca = new javax.swing.JComboBox<>();
        lblMarca = new javax.swing.JLabel();
        txtCodigoFabricante = new javax.swing.JTextField();
        lblCodFab = new javax.swing.JLabel();
        txtCodigoOriginal = new javax.swing.JTextField();
        lblCodOri = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblDesc = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDataCadastro = new javax.swing.JFormattedTextField();
        lblGrupo = new javax.swing.JLabel();
        cmbGrupo = new javax.swing.JComboBox<>();
        cmbSubgrupo = new javax.swing.JComboBox<>();
        lblSubgrupo = new javax.swing.JLabel();
        txtLucro = new javax.swing.JSpinner();
        lblPrecoCusto1 = new javax.swing.JLabel();
        lblPrecoCusto2 = new javax.swing.JLabel();
        chkHabilitado = new javax.swing.JCheckBox();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltarCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestão de Produtos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        pnlTitulo.setBackground(new java.awt.Color(246, 91, 92));

        lblTitulo.setBackground(new java.awt.Color(246, 91, 92));
        lblTitulo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/produto_36px.png"))); // NOI18N
        lblTitulo.setText("Gestão de Produtos");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlItens.setBackground(new java.awt.Color(233, 234, 234));

        jPanel1.setBackground(new java.awt.Color(233, 234, 234));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        txtQtdDisponivel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtQtdDisponivel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtdDisponivelKeyTyped(evt);
            }
        });

        lblQtdAtual.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblQtdAtual.setText("<html>Qtde. Disponível: <body> <span style=\"color: red;\">*</span></body></html>");

        txtQtdMinima.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtQtdMinima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtdMinimaKeyTyped(evt);
            }
        });

        lblQtdMin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblQtdMin.setText("<html>Qtde. Minima: <body> <span style=\"color: red;\">*</span></body></html>");

        txtPrecoCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPrecoCusto.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtPrecoCusto.setText("R$ 0,00");
        txtPrecoCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecoCustoKeyReleased(evt);
            }
        });

        lblPrecoCusto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrecoCusto.setText("<html>Preço de Custo: <body> <span style=\"color: red;\">*</span></body></html>");

        txtPrecoVenda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPrecoVenda.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtPrecoVenda.setText("R$ 0,00");
        txtPrecoVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecoVendaKeyReleased(evt);
            }
        });

        lblPrecoVenda.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrecoVenda.setText("<html>Preço de Venda: <body> <span style=\"color: red;\">*</span></body></html>");

        txtDimensoes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDimensoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDimensoesKeyTyped(evt);
            }
        });

        lblDimensoes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDimensoes.setText("Dimensões: ");

        txtLocalizacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLocalizacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLocalizacaoKeyTyped(evt);
            }
        });

        lblLocalizacao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblLocalizacao.setText("Localização: ");

        cmbUnidadeMedida.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblUnidadeMedida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUnidadeMedida.setText("<html><body><span style=\"text-decoration: underline; color: #0000CD;\">UN:</span><span style=\"color: red;\"> *</span></body></html>");
        lblUnidadeMedida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUnidadeMedidaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUnidadeMedidaMousePressed(evt);
            }
        });

        cmbMarca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblMarca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMarca.setText("<html><body><span style=\"text-decoration: underline; color: #0000CD;\">Marca:</span><span style=\"color: red;\"> *</span></body></html>");
        lblMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMarcaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMarcaMousePressed(evt);
            }
        });

        txtCodigoFabricante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodigoFabricante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoFabricanteKeyTyped(evt);
            }
        });

        lblCodFab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCodFab.setText("Código do Fabricante: ");

        txtCodigoOriginal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodigoOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoOriginalKeyTyped(evt);
            }
        });

        lblCodOri.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCodOri.setText("Código Original: ");

        txtDescricao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyTyped(evt);
            }
        });

        lblDesc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDesc.setText("<html>Descrição: <body> <span style=\"color: red;\">*</span></body></html>");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("<html>Data de Cadastro: <body> <span style=\"color: red;\">*</span></body></html>");

        try {
            txtDataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCadastro.setFocusable(false);
        txtDataCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblGrupo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGrupo.setText("<html><body><span style=\"text-decoration: underline; color: #0000CD;\">Grupo:</span><span style=\"color: red;\"> *</span></body></html>");
        lblGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGrupoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblGrupoMousePressed(evt);
            }
        });

        cmbGrupo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGrupoActionPerformed(evt);
            }
        });

        cmbSubgrupo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblSubgrupo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSubgrupo.setText("<html><body><span style=\"text-decoration: underline; color: #0000CD;\">Subgrupo:</span><span style=\"color: red;\"> *</span></body></html>");
        lblSubgrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSubgrupoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSubgrupoMousePressed(evt);
            }
        });

        txtLucro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLucro.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));
        txtLucro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtLucroStateChanged(evt);
            }
        });

        lblPrecoCusto1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrecoCusto1.setText("<html>Lucro: <body> <span style=\"color: red;\">*</span></body></html>");

        lblPrecoCusto2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrecoCusto2.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDimensoes, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDimensoes, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 369, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSubgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbSubgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCodFab)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtCodigoFabricante))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodOri)
                                    .addComponent(txtCodigoOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cmbUnidadeMedida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblUnidadeMedida)
                                                .addGap(40, 40, 40)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblQtdMin, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                            .addComponent(txtQtdMinima))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblQtdAtual)
                                            .addComponent(txtQtdDisponivel))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblPrecoCusto2))
                                            .addComponent(lblPrecoCusto1)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(txtDataCadastro)
                                    .addComponent(lblPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecoVenda))))
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtDataCadastro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecoCusto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecoCusto2)))
                    .addComponent(lblUnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblQtdAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtQtdDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblQtdMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtQtdMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbUnidadeMedida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSubgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSubgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCodFab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCodOri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLocalizacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDimensoes)
                        .addGap(29, 29, 29))
                    .addComponent(txtDimensoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        chkHabilitado.setBackground(new java.awt.Color(233, 234, 234));
        chkHabilitado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chkHabilitado.setSelected(true);
        chkHabilitado.setText("Habilitado");
        chkHabilitado.setFocusable(false);

        btnNovo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setFocusable(false);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inserir.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setFocusable(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setFocusable(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVoltarCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVoltarCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltar_cancelar.png"))); // NOI18N
        btnVoltarCancelar.setText("Voltar");
        btnVoltarCancelar.setFocusable(false);
        btnVoltarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCancelarActionPerformed(evt);
            }
        });

        txtObservacoes.setColumns(20);
        txtObservacoes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtObservacoes.setRows(5);
        txtObservacoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObservacoesKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtObservacoes);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Observações:");

        javax.swing.GroupLayout pnlItensLayout = new javax.swing.GroupLayout(pnlItens);
        pnlItens.setLayout(pnlItensLayout);
        pnlItensLayout.setHorizontalGroup(
            pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlItensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlItensLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(chkHabilitado))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlItensLayout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltarCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(pnlItensLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlItensLayout.setVerticalGroup(
            pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensLayout.createSequentialGroup()
                .addComponent(chkHabilitado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnVoltarCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(835, 573));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGrupoActionPerformed
        if(cmbGrupo.getSelectedItem()!=null){
            carregarSubgrupo(null);
        }
    }//GEN-LAST:event_cmbGrupoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(!(cmbMarca.getSelectedItem()==null) && !(cmbUnidadeMedida.getSelectedItem()==null) && !(cmbGrupo.getSelectedItem()==null) && !(cmbSubgrupo.getSelectedItem()==null) && !StringUtils.isNullOrEmpty(txtDescricao.getText().trim()) && !StringUtils.isNullOrEmpty(txtDataCadastro.getText()) && !txtDataCadastro.getText().equals("  /  /       :  ") && !StringUtils.isNullOrEmpty(txtQtdMinima.getText().trim()) && !StringUtils.isNullOrEmpty(txtQtdDisponivel.getText().trim())) {
            if(!(Float.parseFloat(Preco.precoParaBanco(txtPrecoVenda.getText()))<Float.parseFloat(Preco.precoParaBanco(txtPrecoCusto.getText())))){
                Produto p = new Produto();
                    if(chkHabilitado.isSelected())
                        p.setIsHabilitado(1);
                    else p.setIsHabilitado(0);
                p.setDescricao(txtDescricao.getText().trim());
                p.setMarca((Marca)cmbMarca.getSelectedItem());
                p.setDataCadastro(txtDataCadastro.getText());
                p.setUnidadeMedida((UnidadeMedida)cmbUnidadeMedida.getSelectedItem());
                p.setQtdMinima(Integer.parseInt(txtQtdMinima.getText().trim()));
                p.setQtdDisponivel(Integer.parseInt(txtQtdDisponivel.getText().trim()));
                p.setPrecoCompra(Float.parseFloat(Preco.precoParaBanco(txtPrecoCusto.getText())));
                p.setPrecoVenda(Float.parseFloat(Preco.precoParaBanco(txtPrecoVenda.getText())));
                p.setSubgrupo((Subgrupo)cmbSubgrupo.getSelectedItem());
                p.setCodigoFabricante(txtCodigoFabricante.getText().trim());
                p.setCodigoOriginal(txtCodigoOriginal.getText().trim());
                p.setLocalizacao(txtLocalizacao.getText().trim());
                p.setDimensoes(txtDimensoes.getText().trim());
                p.setObservacoes(txtObservacoes.getText().trim());
                ProdutoDAO dao = new ProdutoDAO();
                    if(!this.editando){
                        if(dao.adicionaProduto(p)){
                            habilitaBotoes();
                            p.setIdProduto(dao.getLastCodeProduto());
                            tp.produtoTableModel.addRow(p);
                            JOptionPane.showMessageDialog(this, "Registro incluído com sucesso!", "Caixa de Diálogo", 1);
                            this.dispose();
                        }
                    } else {
                        p.setIdProduto(this.produtoCarregado.getIdProduto());
                        if(dao.atualizaProduto(p)){  
                            this.editando = false;
                            habilitaBotoes();
                            tp.carregarTabelaProdutos();
                            JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!", "Caixa de Diálogo", 1);
                            this.dispose();
                        }
                    }
                this.produtoCarregado = p;
            } else JOptionPane.showMessageDialog(null, "O preço de venda é menor que o preço de custo!", "Caixa de Diálogo", 0);
        } else JOptionPane.showMessageDialog(null, "Há campos obrigatórios que não foram preenchidos!", "Caixa de Diálogo", 0);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.editando = true;
        desabilitaBotoes();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Você quer mesmo excluir este registro?", "Caixa de Confirmação", 0)==0){
            ProdutoDAO dao = new ProdutoDAO();
            if(dao.removeProduto(produtoCarregado)){
                tp.produtoTableModel.removeRow(produtoCarregado);
                JOptionPane.showMessageDialog(this, "Registro excluído com sucesso!", "Caixa de Diálogo", 1);
                this.dispose();
            } else JOptionPane.showMessageDialog(null, "Não foi possível excluir este registro.\nProvavelmente há compras e/ou vendas vinculadas a ele!", "Caixa de Afirmação", 0);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCancelarActionPerformed
        if(this.editando){
            if(JOptionPane.showConfirmDialog(this, "Você quer mesmo desfazer as alterações deste registro?", "Caixa de Confirmação", 0)==0){
                habilitaBotoes();
                this.editando = false;
                carregarProduto();
            }
        } else if(JOptionPane.showConfirmDialog(this, "Você quer mesmo voltar à tela anterior?", "Caixa de Confirmação", 0)==0)
        this.dispose();
    }//GEN-LAST:event_btnVoltarCancelarActionPerformed

    private void txtObservacoesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObservacoesKeyTyped
        if(txtObservacoes.getText().length()>=65535){
            evt.consume();
            txtObservacoes.setText(txtObservacoes.getText().substring(0, 65535));
        }
    }//GEN-LAST:event_txtObservacoesKeyTyped

    private void txtDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar()) && !"-/.,\"'".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtDescricao.getText().length()>=50)
            evt.consume();
    }//GEN-LAST:event_txtDescricaoKeyTyped

    private void txtQtdMinimaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdMinimaKeyTyped
        if (!Character.isDigit(evt.getKeyChar()))
            evt.consume();
        
        if(txtQtdMinima.getText().length()>=13)
            evt.consume();
    }//GEN-LAST:event_txtQtdMinimaKeyTyped

    private void txtQtdDisponivelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdDisponivelKeyTyped
        if (!Character.isDigit(evt.getKeyChar()))
            evt.consume();
        
        if(txtQtdDisponivel.getText().length()>=13)
            evt.consume();
    }//GEN-LAST:event_txtQtdDisponivelKeyTyped

    private void txtCodigoFabricanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoFabricanteKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar()) && !"-/.'".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtCodigoFabricante.getText().length()>=25)
            evt.consume();
    }//GEN-LAST:event_txtCodigoFabricanteKeyTyped

    private void txtCodigoOriginalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoOriginalKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar()) && !"-/.'".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtCodigoOriginal.getText().length()>=25)
            evt.consume();
    }//GEN-LAST:event_txtCodigoOriginalKeyTyped

    private void txtLocalizacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLocalizacaoKeyTyped
        if (!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar()) && !"-/.'".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtLocalizacao.getText().length()>=25)
            evt.consume();
    }//GEN-LAST:event_txtLocalizacaoKeyTyped

    private void txtDimensoesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDimensoesKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !"-/.,\"xX".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(evt.getKeyChar()=='.') //. por ,
            evt.setKeyChar(',');
        
        if(evt.getKeyChar()=='x') //x minúsculo para X maiúsculo
            evt.setKeyChar('X');
        
        if(txtDimensoes.getText().length()>=25)
            evt.consume();
    }//GEN-LAST:event_txtDimensoesKeyTyped

    private void txtLucroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtLucroStateChanged
        txtPrecoVenda.setText(String.format("%.2f", Float.parseFloat(Preco.precoParaBanco(txtPrecoCusto.getText()))* ((float) txtLucro.getValue())/100+(Float.parseFloat(Preco.precoParaBanco(txtPrecoCusto.getText())))));
    }//GEN-LAST:event_txtLucroStateChanged

    private void txtPrecoVendaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecoVendaKeyReleased
        txtLucro.setValue((Float.parseFloat(Preco.precoParaBanco(txtPrecoVenda.getText()))/Float.parseFloat(Preco.precoParaBanco(txtPrecoCusto.getText()))-1)*100);
    }//GEN-LAST:event_txtPrecoVendaKeyReleased

    private void txtPrecoCustoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecoCustoKeyReleased
        txtLucro.setValue((Float.parseFloat(Preco.precoParaBanco(txtPrecoVenda.getText()))/Float.parseFloat(Preco.precoParaBanco(txtPrecoCusto.getText()))-1)*100);
    }//GEN-LAST:event_txtPrecoCustoKeyReleased

    private void lblUnidadeMedidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUnidadeMedidaMouseEntered
        if(cmbUnidadeMedida.isEnabled())
            lblUnidadeMedida.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblUnidadeMedidaMouseEntered

    private void lblMarcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMarcaMouseEntered
        if(cmbMarca.isEnabled())
            lblMarca.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblMarcaMouseEntered

    private void lblGrupoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGrupoMouseEntered
        if(cmbGrupo.isEnabled())
            lblGrupo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblGrupoMouseEntered

    private void lblSubgrupoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSubgrupoMouseEntered
        if(cmbSubgrupo.isEnabled())
            lblSubgrupo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblSubgrupoMouseEntered

    private void lblMarcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMarcaMousePressed
        if(cmbMarca.isEnabled()){
            this.setModal(false);
            TelaMarca tm = new TelaMarca(null, true);
            tm.setVisible(true);
            this.setModal(true);
            carregaMarca(null);
            cmbMarca.setSelectedItem(null);
        }
    }//GEN-LAST:event_lblMarcaMousePressed

    private void lblUnidadeMedidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUnidadeMedidaMousePressed
        if(cmbUnidadeMedida.isEnabled()){            
            this.setModal(false);
            TelaUnidadeMedida tum = new TelaUnidadeMedida(null, true);
            tum.setVisible(true);
            this.setModal(true);
            carregarUnidadeMedida(null);
            cmbUnidadeMedida.setSelectedItem(null);
        }
    }//GEN-LAST:event_lblUnidadeMedidaMousePressed

    private void lblGrupoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGrupoMousePressed
        if(cmbGrupo.isEnabled()){
            this.setModal(false);
            TelaGrupoSubgrupo tgsbg = new TelaGrupoSubgrupo(null, true);
            tgsbg.setVisible(true);
            this.setModal(true);
            carregarGrupo(null);
            cmbGrupo.setSelectedItem(null);
            cmbSubgrupo.setSelectedItem(null);
        }
    }//GEN-LAST:event_lblGrupoMousePressed

    private void lblSubgrupoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSubgrupoMousePressed
        if(cmbSubgrupo.isEnabled()){            
            this.setModal(false);
            TelaGrupoSubgrupo tgsbg = new TelaGrupoSubgrupo(null, true);
            tgsbg.setVisible(true);
            this.setModal(true);
            carregarGrupo(null);
            cmbGrupo.setSelectedItem(null);
            cmbSubgrupo.setSelectedItem(null);
        }
    }//GEN-LAST:event_lblSubgrupoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaProduto dialog = new TelaProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltarCancelar;
    private javax.swing.JCheckBox chkHabilitado;
    private javax.swing.JComboBox<Object> cmbGrupo;
    private javax.swing.JComboBox<Object> cmbMarca;
    private javax.swing.JComboBox<Object> cmbSubgrupo;
    private javax.swing.JComboBox<Object> cmbUnidadeMedida;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodFab;
    private javax.swing.JLabel lblCodOri;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDimensoes;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblLocalizacao;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblPrecoCusto;
    private javax.swing.JLabel lblPrecoCusto1;
    private javax.swing.JLabel lblPrecoCusto2;
    private javax.swing.JLabel lblPrecoVenda;
    private javax.swing.JLabel lblQtdAtual;
    private javax.swing.JLabel lblQtdMin;
    private javax.swing.JLabel lblSubgrupo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUnidadeMedida;
    private javax.swing.JPanel pnlItens;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtCodigoFabricante;
    private javax.swing.JTextField txtCodigoOriginal;
    private javax.swing.JFormattedTextField txtDataCadastro;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDimensoes;
    private javax.swing.JTextField txtLocalizacao;
    private javax.swing.JSpinner txtLucro;
    private javax.swing.JTextArea txtObservacoes;
    private javax.swing.JTextField txtPrecoCusto;
    private javax.swing.JTextField txtPrecoVenda;
    private javax.swing.JTextField txtQtdDisponivel;
    private javax.swing.JTextField txtQtdMinima;
    // End of variables declaration//GEN-END:variables
    private String definirDataCadastro (){
	DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm"); 
	Date date = new Date(); 
	return dateFormat.format(date); 
    }
    
    private void carregarUnidadeMedida(UnidadeMedida unidadeMedida){
        cmbUnidadeMedida.removeAllItems();
        UnidadeMedidaDAO dao = new UnidadeMedidaDAO();
        for(UnidadeMedida un:dao.getListaUnidadeMedida()){
            cmbUnidadeMedida.addItem(un);
                if(unidadeMedida!=null && un.getIdUnidadeMedida()==unidadeMedida.getIdUnidadeMedida())
                    cmbUnidadeMedida.setSelectedItem(un);
        }
    }
    private void carregarGrupo(Grupo grupo){
        cmbGrupo.removeAllItems();
        GrupoDAO dao = new GrupoDAO();
        for(Grupo gp:dao.getListaGrupo()){
            cmbGrupo.addItem(gp);
                if(grupo!=null && gp.getIdGrupo()==grupo.getIdGrupo())
                    cmbGrupo.setSelectedItem(gp);
        }
    }
    
    private void carregarSubgrupo(Subgrupo subgrupo){
        cmbSubgrupo.removeAllItems();
        SubgrupoDAO dao = new SubgrupoDAO();
        for(Subgrupo sg:dao.getListaGrupo((Grupo)cmbGrupo.getSelectedItem())){
            cmbSubgrupo.addItem(sg);
                if(subgrupo!=null && sg.getIdSubgrupo()==subgrupo.getIdSubgrupo())
                    cmbSubgrupo.setSelectedItem(sg);
        }
    }
    
    private void carregaMarca(Marca marca){
        cmbMarca.removeAllItems();
        MarcaDAO dao = new MarcaDAO();
        for(Marca m:dao.getListaMarca()){
            cmbMarca.addItem(m);
                if(marca!=null && m.getIdMarca()==marca.getIdMarca())
                    cmbMarca.setSelectedItem(m);
        }
    }
    
    private void habilitaBotoes(){
        desabilitaCampos();
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }
    
    private void desabilitaBotoes(){
        habilitaCampos();
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
    
    private void desabilitaCampos(){
        chkHabilitado.setEnabled(false);
        txtDescricao.setEditable(false);
        cmbMarca.setEnabled(false);
        cmbUnidadeMedida.setEnabled(false);
        txtQtdMinima.setEditable(false);
        txtQtdDisponivel.setEditable(false);
        txtPrecoCusto.setEditable(false);
        txtLucro.setEnabled(false);
        txtPrecoVenda.setEditable(false);
        cmbGrupo.setEnabled(false);
        cmbSubgrupo.setEnabled(false);
        txtCodigoFabricante.setEditable(false);
        txtCodigoOriginal.setEditable(false);
        txtLocalizacao.setEditable(false);
        txtDimensoes.setEditable(false);
        txtObservacoes.setEditable(false);
        txtObservacoes.setBackground(null);
    }
    
    private void habilitaCampos(){
        chkHabilitado.setEnabled(true);
        txtDescricao.setEditable(true);
        cmbMarca.setEnabled(true);
        cmbUnidadeMedida.setEnabled(true);
        txtQtdMinima.setEditable(true);
        txtQtdDisponivel.setEditable(true);
        txtPrecoCusto.setEditable(true);
        txtLucro.setEnabled(true);
        txtPrecoVenda.setEditable(true);
        cmbGrupo.setEnabled(true);
        cmbSubgrupo.setEnabled(true);
        txtCodigoFabricante.setEditable(true);
        txtCodigoOriginal.setEditable(true);
        txtLocalizacao.setEditable(true);
        txtDimensoes.setEditable(true);
        txtObservacoes.setEditable(true);
        txtObservacoes.setBackground(branco);
        txtDescricao.requestFocus();
    }
    
    private void limpaCampos(){
        desabilitaBotoes();
        chkHabilitado.setSelected(true);
        txtDescricao.setText(null);
        cmbMarca.setSelectedItem(null);
        txtDataCadastro.setText(definirDataCadastro());
        cmbUnidadeMedida.setSelectedItem(null);
        txtQtdMinima.setText(null);
        txtQtdDisponivel.setText(null);
        txtPrecoCusto.setText(null);
        txtPrecoVenda.setText(null);
        cmbGrupo.setSelectedItem(null);
        cmbSubgrupo.setSelectedItem(null);
        txtCodigoFabricante.setText(null);;
        txtCodigoOriginal.setText(null);
        txtLocalizacao.setText(null);
        txtDimensoes.setText(null);
        txtObservacoes.setText(null);
    }
    
    private void carregarProduto(){
        if(produtoCarregado.getIsHabilitado()==1)
           chkHabilitado.setSelected(true);
        else chkHabilitado.setSelected(false);
        txtDescricao.setText(produtoCarregado.getDescricao());
        carregaMarca(produtoCarregado.getMarca());
        txtDataCadastro.setText(produtoCarregado.getDataCadastro());
        carregarUnidadeMedida(produtoCarregado.getUnidadeMedida());
        txtQtdMinima.setText(Integer.toString(produtoCarregado.getQtdMinima()));
        txtQtdDisponivel.setText(Integer.toString(produtoCarregado.getQtdDisponivel()));
        txtPrecoCusto.setText(String.format("%.2f", produtoCarregado.getPrecoCompra()));
        txtPrecoVenda.setText(String.format("%.2f", produtoCarregado.getPrecoVenda()));
        txtLucro.setValue((Float.parseFloat(Preco.precoParaBanco(txtPrecoVenda.getText()))/Float.parseFloat(Preco.precoParaBanco(txtPrecoCusto.getText()))-1)*100);
        carregarGrupo(produtoCarregado.getSubgrupo().getGrupo());
        carregarSubgrupo(produtoCarregado.getSubgrupo());
        txtCodigoFabricante.setText(produtoCarregado.getCodigoFabricante());
        txtCodigoOriginal.setText(produtoCarregado.getCodigoOriginal());
        txtLocalizacao.setText(produtoCarregado.getLocalizacao());
        txtDimensoes.setText(produtoCarregado.getDimensoes());
        txtObservacoes.setText(produtoCarregado.getObservacoes());
    }
}