/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.view;

import com.mysql.jdbc.StringUtils;
import java.awt.Color;
import java.awt.Cursor;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.bean.Cargo;
import model.bean.Cidade;
import model.bean.Empresa;
import model.bean.Estado;
import others.Preco;
import model.bean.Usuario;
import model.dao.CargoDAO;
import model.dao.CidadeDAO;
import model.dao.EmpresaDAO;
import model.dao.EstadoDAO;
import model.dao.PessoaDAO;
import model.dao.PessoaFisicaDAO;
import model.dao.UsuarioDAO;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import others.JNumberFormatField;

/**
 *
 * @author Lucas Matheus
 */
public class TelaUsuario extends javax.swing.JDialog {

    Color vermelho = new Color(246, 91, 92, 255);
    Color verde = new Color(50, 205, 50, 255);
    Color branco = new Color(255, 255, 255, 255);
    private boolean editando = false;
    private Usuario usuarioCarregado;
    TelaPrincipal tp;
    
    public TelaUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/logoSistema_16px.png")).getImage());
        AutoCompleteDecorator.decorate(cmbEmpresa);
        AutoCompleteDecorator.decorate(cmbCargo);
        AutoCompleteDecorator.decorate(cmbEstado);
        AutoCompleteDecorator.decorate(cmbCidade);
        carregarCargo(null);
        carregarEmpresa(null);
        carregarEstado(null);
        txtDataCadastro.setEditable(false);
        limpaCampos();
    }
    
    public TelaUsuario(java.awt.Frame parent, boolean modal, byte tipo, Usuario usuario) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/logoSistema_16px.png")).getImage());
        this.tp = (TelaPrincipal) parent;
        AutoCompleteDecorator.decorate(cmbEmpresa);
        AutoCompleteDecorator.decorate(cmbCargo);
        AutoCompleteDecorator.decorate(cmbEstado);
        AutoCompleteDecorator.decorate(cmbCidade);
        txtDataCadastro.setEditable(false);
            if(tipo==0){ //novo
                carregarCargo(null);
                carregarEmpresa(null);
                carregarEstado(null);
                limpaCampos();
            } else if (tipo==1){ //visualizar
                this.usuarioCarregado = usuario;
                habilitaBotoes();
                carregarUsuario();
            } else if (tipo==2){ //editando
                this.usuarioCarregado = usuario;
                this.editando = true;
                desabilitaBotoes();
                carregarUsuario();
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApelido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtDataCadastro = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRG = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        txtSenha2 = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        txtSalario = new JNumberFormatField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cmbEmpresa = new javax.swing.JComboBox<>();
        lblEmpresa = new javax.swing.JLabel();
        cmbCargo = new javax.swing.JComboBox<>();
        lblCargo = new javax.swing.JLabel();
        txtComissao = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        txtTelefoneFixo = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        txtTelefoneCelular = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        txtDataNascimento = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JFormattedTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbCidade = new javax.swing.JComboBox<>();
        chkHabilitado = new javax.swing.JCheckBox();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnVoltarCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestão de Usuários");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(246, 91, 92));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario_36px.png"))); // NOI18N
        jLabel1.setText("Gestão de Usuários");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(233, 234, 234));

        jPanel3.setBackground(new java.awt.Color(233, 234, 234));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("<html>Nome: <body> <span style=\"color: red;\">*</span></body></html>");

        txtApelido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtApelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApelidoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Apelido:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("<html>Sexo: <body> <span style=\"color: red;\">*</span></body></html>");

        cmbSexo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        cmbSexo.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("<html>Data de Cadastro: <body> <span style=\"color: red;\">*</span></body></html>");

        try {
            txtDataCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCadastro.setFocusable(false);
        txtDataCadastro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("<html>Data de Nasc: <body> <span style=\"color: red;\">*</span></body></html>");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPFKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("<html>CPF: <body> <span style=\"color: red;\">*</span></body></html>");

        txtRG.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRGKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("RG:");

        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("E-Mail:");

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("<html>Usuário: <body> <span style=\"color: red;\">*</span></body></html>");

        txtSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSenhaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSenhaKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("<html>Senha: <body> <span style=\"color: red;\">*</span></body></html>");

        txtSenha2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSenha2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSenha2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSenha2KeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("<html>Conf. de Senha: <body> <span style=\"color: red;\">*</span></body></html>");

        txtSalario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSalario.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtSalario.setText("R$ 0,00");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("<html>Salário: <body> <span style=\"color: red;\">*</span></body></html>");

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("<html>Comissão: <body> <span style=\"color: red;\">*</span></body></html>");

        cmbEmpresa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmpresaActionPerformed(evt);
            }
        });

        lblEmpresa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEmpresa.setText("<html><body><span style=\"text-decoration: underline; color: #0000CD;\">Empresa:</span><span style=\"color: red;\"> *</span></body></html>");
        lblEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEmpresaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEmpresaMousePressed(evt);
            }
        });

        cmbCargo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblCargo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCargo.setText("<html><body><span style=\"text-decoration: underline; color: #0000CD;\">Cargo:</span><span style=\"color: red;\"> *</span></body></html>");
        lblCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCargoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCargoMousePressed(evt);
            }
        });

        txtComissao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtComissao.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(100.0f), Float.valueOf(5.0f)));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setText("%");

        try {
            txtTelefoneFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneFixo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefoneFixo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefoneFixoKeyReleased(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("Tel. Fixo:");

        try {
            txtTelefoneCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneCelular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefoneCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefoneCelularKeyReleased(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setText("Tel. Celular:");

        txtDataNascimento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cmbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(15, 15, 15))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23)
                            .addComponent(txtComissao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel11))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNome)
                            .addComponent(txtEmail))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefoneFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(txtTelefoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDataCadastro)
                            .addComponent(txtDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCPF)
                                    .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefoneFixo)
                            .addComponent(txtTelefoneCelular)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(1, 1, 1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jPanel4.setBackground(new java.awt.Color(233, 234, 234));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("<html>Logradouro: <body> <span style=\"color: red;\">*</span></body></html>");

        txtLogradouro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtLogradouro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLogradouroKeyTyped(evt);
            }
        });

        txtNumero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("<html>Número: <body> <span style=\"color: red;\">*</span></body></html>");

        txtComplemento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtComplementoKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Complemento:");

        txtBairro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBairroKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("<html>Bairro: <body> <span style=\"color: red;\">*</span></body></html>");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("<html>CEP: <body> <span style=\"color: red;\">*</span></body></html>");

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.setText("");
        txtCEP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cmbEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbEstado.setToolTipText("");
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("<html>Estado: <body> <span style=\"color: red;\">*</span></body></html>");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("<html>Cidade: <body> <span style=\"color: red;\">*</span></body></html>");

        cmbCidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbCidade.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(439, 439, 439)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbEstado)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCidade))))
        );

        chkHabilitado.setBackground(new java.awt.Color(233, 234, 234));
        chkHabilitado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chkHabilitado.setSelected(true);
        chkHabilitado.setText("Habilitado");
        chkHabilitado.setFocusable(false);

        btnNovo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setFocusable(false);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inserir.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setFocusable(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setFocusable(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVoltarCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVoltarCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltar_cancelar.png"))); // NOI18N
        btnVoltarCancelar.setText("Voltar");
        btnVoltarCancelar.setFocusable(false);
        btnVoltarCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCancelarActionPerformed(evt);
            }
        });

        txtObservacoes.setColumns(20);
        txtObservacoes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtObservacoes.setRows(5);
        txtObservacoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtObservacoesKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtObservacoes);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setText("Observações:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(chkHabilitado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltarCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(chkHabilitado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnVoltarCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(835, 719));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtApelidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApelidoKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()))
            evt.consume();
        
        if(txtApelido.getText().length()>=20)
            evt.consume();
    }//GEN-LAST:event_txtApelidoKeyTyped

    private void txtRGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRGKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar()) && !".-".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtRG.getText().length()>=20)
            evt.consume();
    }//GEN-LAST:event_txtRGKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        if(txtEmail.getText().length()>=70)
            evt.consume();
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtLogradouroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLogradouroKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !".'".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtLogradouro.getText().length()>=70)
            evt.consume();
    }//GEN-LAST:event_txtLogradouroKeyTyped

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
        if(!Character.isDigit(evt.getKeyChar()) && !"-/".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtNumero.getText().length()>=8)
            evt.consume();
    }//GEN-LAST:event_txtNumeroKeyTyped

    private void txtComplementoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !"-/.".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtComplemento.getText().length()>=30)
            evt.consume();
    }//GEN-LAST:event_txtComplementoKeyTyped

    private void txtBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !".'".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtBairro.getText().length()>=30)
            evt.consume();
    }//GEN-LAST:event_txtBairroKeyTyped

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar()))
            evt.consume();
        
        if(txtUsuario.getText().length()>=20)
            evt.consume();
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        carregarCidade((Estado) cmbEstado.getSelectedItem());
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void txtCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyReleased
        if(txtCPF.isEditable()){
            if(!validarCPF())
                txtCPF.setBackground(vermelho);
            else txtCPF.setBackground(verde);
        } else txtCPF.setBackground(null);
    }//GEN-LAST:event_txtCPFKeyReleased

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !"'".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtNome.getText().length()>=50)
            evt.consume();
    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar()))
            evt.consume();

        if(new String(txtSenha.getPassword()).length()>=20)
            evt.consume();
    }//GEN-LAST:event_txtSenhaKeyTyped

    private void txtSenha2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenha2KeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar()) && !Character.isDigit(evt.getKeyChar()))
            evt.consume();
        
        if(new String(txtSenha2.getPassword()).length()>=20)
            evt.consume();
    }//GEN-LAST:event_txtSenha2KeyTyped

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(!(cmbEstado.getSelectedItem()==null) && !(cmbCidade.getSelectedItem()==null) && !(cmbEmpresa.getSelectedItem()==null) && !(cmbCargo.getSelectedItem()==null) && !StringUtils.isNullOrEmpty(txtNome.getText().trim()) && !StringUtils.isNullOrEmpty(txtDataCadastro.getText())
            && !txtDataCadastro.getText().equals("  /  /       :  ") && !StringUtils.isNullOrEmpty(txtCPF.getText()) && !txtCPF.getText().equals("   .   .   -  ") && !StringUtils.isNullOrEmpty(txtLogradouro.getText().trim()) && !StringUtils.isNullOrEmpty(txtNumero.getText().trim())
            && !StringUtils.isNullOrEmpty(txtCEP.getText()) && !txtCEP.getText().equals("     -   ") && !StringUtils.isNullOrEmpty(txtBairro.getText().trim()) && !StringUtils.isNullOrEmpty(txtUsuario.getText().trim())
            && !StringUtils.isNullOrEmpty(new String(txtSenha.getPassword()).trim()) && !StringUtils.isNullOrEmpty(new String(txtSenha2.getPassword()).trim())){
            if(txtDataNascimento.getDate()!=null){
                if(validarCPF()){
                    if(validarSenha()){
                    Usuario usuario = new Usuario();
                        if(chkHabilitado.isSelected())
                            usuario.setIsHabilitado(1);
                        else usuario.setIsHabilitado(0);
                    usuario.setNome(txtNome.getText().trim());
                    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy"); 
                    usuario.setDataNascimento(dateFormat.format(txtDataNascimento.getDate()));
                    usuario.setDataCadastro(txtDataCadastro.getText());
                    usuario.setApelido(txtApelido.getText().trim());
                        if(cmbSexo.getSelectedItem().toString().equals("Masculino"))
                            usuario.setSexo("M");
                        else usuario.setSexo("F");
                    usuario.setCpf(txtCPF.getText());
                    usuario.setRg(txtRG.getText().trim());
                    usuario.setEmail(txtEmail.getText().trim());
                    usuario.setTelefoneFixo(txtTelefoneFixo.getText());
                    usuario.setTelefoneCelular(txtTelefoneCelular.getText());
                    usuario.setLogradouro(txtLogradouro.getText().trim());
                    usuario.setNumero(txtNumero.getText().trim());
                    usuario.setCep(txtCEP.getText());
                    usuario.setComplemento(txtComplemento.getText().trim());
                    usuario.setBairro(txtBairro.getText().trim());
                    usuario.setCidade((Cidade) cmbCidade.getSelectedItem());
                    usuario.setLogin(txtUsuario.getText().trim());
                    usuario.setSenha(new String (txtSenha.getPassword()).trim());
                    usuario.setSalario(Float.parseFloat(Preco.precoParaBanco(txtSalario.getText())));
                    usuario.setComissao((float) txtComissao.getValue());
                    usuario.setEmpresa((Empresa) cmbEmpresa.getSelectedItem());
                    usuario.setCargo((Cargo) cmbCargo.getSelectedItem());
                    usuario.setObservacoes(txtObservacoes.getText().trim());
                    UsuarioDAO dao = new UsuarioDAO();
                    habilitaBotoes();
                        if(!this.editando){
                            dao.adicionaUsuario(usuario);
                            usuario.setIdPessoa(dao.getLastCodeUsuario());
                            PessoaFisicaDAO daopf = new PessoaFisicaDAO();
                            usuario.setIdPessoaFisica(daopf.getLastCodePessoaFisica());
                            PessoaDAO daop = new PessoaDAO();
                            usuario.setIdPessoa(daop.getLastCodePessoa());
                            tp.usuarioTableModel.addRow(usuario);
                            JOptionPane.showMessageDialog(this, "Registro incluído com sucesso!", "Caixa de Diálogo", 1);
                            this.dispose();
                        } else {
                            usuario.setIdPessoa(usuarioCarregado.getIdPessoa());
                            usuario.setIdPessoaFisica(usuarioCarregado.getIdPessoaFisica());
                            usuario.setIdUsuario(usuarioCarregado.getIdUsuario());
                            dao.atualizaUsuario(usuario);
                            tp.carregarTabelaUsuarios();
                            this.editando = false;
                            JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!", "Caixa de Diálogo", 1);
                            this.dispose();
                        }
                    this.usuarioCarregado = usuario;
                    } else JOptionPane.showMessageDialog(null, "As senhas não coincidem!", "Caixa de Diálogo", 0);
                } else JOptionPane.showMessageDialog(null, "O CPF digitado não é válido!", "Caixa de Diálogo", 0);
            } else JOptionPane.showMessageDialog(null, "A data de nascimento não foi digitada ou não é válida!", "Caixa de Diálogo", 0);
        } else JOptionPane.showMessageDialog(null, "Há campos obrigatórios que não foram preenchidos!", "Caixa de Diálogo", 0);
        

        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.editando = true;
        desabilitaBotoes();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Você quer mesmo excluir este registro?", "Caixa de Confirmação", 0)==0){
            UsuarioDAO dao = new UsuarioDAO();
            if(dao.removeUsuario(usuarioCarregado)){
                tp.usuarioTableModel.removeRow(usuarioCarregado);
                JOptionPane.showMessageDialog(this, "Registro excluído com sucesso!", "Caixa de Diálogo", 1);
                this.dispose();
            } else JOptionPane.showMessageDialog(null, "Não foi possível excluir este registro.\nProvavelmente há compras e/ou vendas vinculadas a ele!", "Caixa de Afirmação", 0);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCancelarActionPerformed
        if(this.editando){
            if(JOptionPane.showConfirmDialog(this, "Você quer mesmo desfazer as alterações deste registro?", "Caixa de Confirmação", 0)==0){
                habilitaBotoes();
                this.editando = false;
                carregarUsuario();
            }
        } else if(JOptionPane.showConfirmDialog(this, "Você quer mesmo voltar à tela anterior?", "Caixa de Confirmação", 0)==0)
        this.dispose();
    }//GEN-LAST:event_btnVoltarCancelarActionPerformed

    private void txtSenha2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenha2KeyReleased
        if(!StringUtils.isNullOrEmpty(new String(txtSenha2.getPassword())) ){
            if(txtSenha2.isEditable()){
                if(!validarSenha())
                    txtSenha2.setBackground(vermelho);
                else txtSenha2.setBackground(verde);
            } else txtSenha2.setBackground(null);
        } else txtSenha2.setBackground(branco);
    }//GEN-LAST:event_txtSenha2KeyReleased

    private void txtObservacoesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtObservacoesKeyTyped
        if(txtObservacoes.getText().length()>=65535)
            evt.consume();
    }//GEN-LAST:event_txtObservacoesKeyTyped

    private void txtSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyReleased
        if(!StringUtils.isNullOrEmpty(new String(txtSenha2.getPassword())) ){
            if(txtSenha2.isEditable()){
                if(!validarSenha())
                    txtSenha2.setBackground(vermelho);
                else txtSenha2.setBackground(verde);
            } else txtSenha2.setBackground(null);
        } else txtSenha2.setBackground(branco);
    }//GEN-LAST:event_txtSenhaKeyReleased

    private void lblEmpresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmpresaMouseEntered
        if(cmbEmpresa.isEnabled())
            lblEmpresa.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblEmpresaMouseEntered

    private void lblCargoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCargoMouseEntered
        if(cmbCargo.isEnabled())
            lblCargo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblCargoMouseEntered

    private void lblCargoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCargoMousePressed
        if(cmbCargo.isEnabled()){
            this.setModal(false);
            TelaCargo tc = new TelaCargo(null, true);
            tc.setVisible(true);
            this.setModal(true);
            carregarCargo(null);
            cmbCargo.setSelectedItem(null);
        }
    }//GEN-LAST:event_lblCargoMousePressed

    private void lblEmpresaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmpresaMousePressed
        if(cmbEmpresa.isEnabled()){
            this.setModal(false);
            TelaEmpresa te = new TelaEmpresa(tp, true, (byte) 0, null);
            te.setVisible(true);
            this.setModal(true);
            carregarEmpresa(null);
            cmbEmpresa.setSelectedItem(null); 
        }
    }//GEN-LAST:event_lblEmpresaMousePressed

    private void txtTelefoneFixoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneFixoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneFixoKeyReleased

    private void txtTelefoneCelularKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneCelularKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneCelularKeyReleased

    private void cmbEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmpresaActionPerformed
        if(cmbEmpresa.isEnabled() && cmbEmpresa.getSelectedItem()!=null  && ((Empresa) cmbEmpresa.getSelectedItem()).getIsHabilitado()!=1){
            if(usuarioCarregado!=null && ((Empresa) cmbEmpresa.getSelectedItem()).getIdEmpresa()==usuarioCarregado.getEmpresa().getIdEmpresa())
                return;
            JOptionPane.showMessageDialog(null, "Não foi possível selecionar esta empresa.\nA empresa selecionada está desabilitada!", "Caixa de Afirmação", 0);
            cmbEmpresa.setSelectedItem(null);
        }
    }//GEN-LAST:event_cmbEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaUsuario dialog = new TelaUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltarCancelar;
    private javax.swing.JCheckBox chkHabilitado;
    private javax.swing.JComboBox<Object> cmbCargo;
    private javax.swing.JComboBox<Object> cmbCidade;
    private javax.swing.JComboBox<Object> cmbEmpresa;
    private javax.swing.JComboBox<Object> cmbEstado;
    private javax.swing.JComboBox<String> cmbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JSpinner txtComissao;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtDataCadastro;
    private com.toedter.calendar.JDateChooser txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextArea txtObservacoes;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenha2;
    private javax.swing.JFormattedTextField txtTelefoneCelular;
    private javax.swing.JFormattedTextField txtTelefoneFixo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    
    private String definirDataCadastro (){
	DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm"); 
	Date date = new Date(); 
	return dateFormat.format(date); 
    }

    private void carregarCargo (Cargo c){
        cmbCargo.removeAllItems();
        CargoDAO dao = new CargoDAO();
            for(Cargo cargo:dao.getListaCargo()){
                cmbCargo.addItem(cargo);
                    if(c!=null && cargo.getIdCargo()==c.getIdCargo())
                        cmbCargo.setSelectedItem(cargo);
            }
    }
    
    private void carregarEstado (Estado est){
        EstadoDAO dao = new EstadoDAO();
            for(Estado estado:dao.getListaEstado()){
                cmbEstado.addItem(estado);
                    if(est==null && estado.toString().equals("SP")){
                        cmbEstado.setSelectedItem(estado);
                        carregarCidade(estado);
                    } else if (est!=null && estado.getIdEstado()==est.getIdEstado())
                        cmbEstado.setSelectedItem(estado);
            }
    }
    
    private void carregarCidade (Estado estado){
        cmbCidade.removeAllItems();
        CidadeDAO dao = new CidadeDAO();
            for(Cidade cidade:dao.getListaCidade(estado)){
                cmbCidade.addItem(cidade);
            }
    }   
    
    private void carregarCidade (Cidade cid){
        cmbCidade.removeAllItems();
        CidadeDAO dao = new CidadeDAO();
            for(Cidade cidade:dao.getListaCidade(cid.getEstado())){
                cmbCidade.addItem(cidade);
                    if(cid!=null && cidade.getIdCidade()==cid.getIdCidade())
                        cmbCidade.setSelectedItem(cidade);
            }
    }
    
    private void carregarEmpresa(Empresa emp){
        cmbEmpresa.setEnabled(false);
        cmbEmpresa.removeAllItems();
        EmpresaDAO dao = new EmpresaDAO();
            for(Empresa empresa:dao.getListaEmpresa()){
                cmbEmpresa.addItem(empresa);
                    if(emp!=null && empresa.getIdEmpresa()==emp.getIdEmpresa())
                        cmbEmpresa.setSelectedItem(empresa);
            }
        if(!btnNovo.isEnabled())
            cmbEmpresa.setEnabled(true);
    }
    
    private boolean validarCPF(){
        if(txtCPF.getText().length()!=14)
            return false;
        else {
        int calculo = 0;
            
            for(int i = 0, j=10;i<11;i++)
                    if(i!=3 && i!=7)
                        calculo += ((int) txtCPF.getText().charAt(i)-48)*j--;

            calculo = 11-calculo%11;
                if(calculo==10 || calculo==11)
                    calculo = 0;

            if(((int)txtCPF.getText().charAt(12)-48)==calculo){
                calculo = 0;
                    for(int i = 0, j=11; i<13; i++)
                        if(i!=3 && i!=7 && i!=11)
                            calculo += ((int) txtCPF.getText().charAt(i)-48)*j--;
                calculo = 11-calculo%11;
                    if(calculo==10 || calculo==11)
                        calculo = 0;
                    if(((int)txtCPF.getText().charAt(13)-48)==calculo)
                        return true;
                    else return false;
            } else return false;
        }
    }
    
    private boolean validarSenha(){
        if((new String(txtSenha.getPassword()).isEmpty()) || (new String(txtSenha2.getPassword()).isEmpty()) || (new String(txtSenha.getPassword()).length())!=(new String(txtSenha2.getPassword()).length()))
            return false;
        else {
            if((new String(txtSenha.getPassword())).equals(new String(txtSenha2.getPassword())))
                return true;
            else return false;
        }    
    }

    private void habilitaBotoes(){
        desabilitaCampos();
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }
    
    private void desabilitaBotoes(){
        habilitaCampos();
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }
    
    private void desabilitaCampos(){
        chkHabilitado.setEnabled(false);
        txtNome.setEditable(false);
        txtDataNascimento.setEnabled(false);
        txtApelido.setEditable(false);
        cmbSexo.setEnabled(false);
        txtCPF.setEditable(false);
        txtCPF.setBackground(null);
        txtRG.setEditable(false);
        txtEmail.setEditable(false);
        txtTelefoneFixo.setEditable(false);
        txtTelefoneCelular.setEditable(false);
        cmbEmpresa.setEnabled(false);
        cmbCargo.setEnabled(false);
        txtUsuario.setEditable(false);
        txtSenha.setEditable(false);
        txtSenha2.setEditable(false);
        txtSenha2.setBackground(null);
        txtSalario.setEditable(false);
        txtComissao.setEnabled(false);
        txtLogradouro.setEditable(false);
        txtNumero.setEditable(false);
        txtCEP.setEditable(false);
        txtComplemento.setEditable(false);
        txtBairro.setEditable(false);
        cmbEstado.setEnabled(false);
        cmbCidade.setEnabled(false);
        txtObservacoes.setEditable(false);
        txtObservacoes.setBackground(null);
    }
    
    private void habilitaCampos(){
        chkHabilitado.setEnabled(true);
        txtNome.setEditable(true);
        txtDataNascimento.setEnabled(true);
        txtApelido.setEditable(true);
        cmbSexo.setEnabled(true);
        txtCPF.setEditable(true);
        txtCPF.setBackground(branco);
        txtRG.setEditable(true);
        txtEmail.setEditable(true);
        txtTelefoneFixo.setEditable(true);
        txtTelefoneCelular.setEditable(true);
        cmbEmpresa.setEnabled(true);
        cmbCargo.setEnabled(true);
        txtUsuario.setEditable(true);
        txtSenha.setEditable(true);
        txtSenha2.setEditable(true);
        txtSenha2.setBackground(branco);
        txtSalario.setEditable(true);
        txtComissao.setEnabled(true);
        txtLogradouro.setEditable(true);
        txtNumero.setEditable(true);
        txtCEP.setEditable(true);
        txtComplemento.setEditable(true);
        txtBairro.setEditable(true);
        cmbEstado.setEnabled(true);
        cmbCidade.setEnabled(true);
        txtObservacoes.setEditable(true);
        txtObservacoes.setBackground(branco);
        txtNome.requestFocus();
    }
    
    private void limpaCampos(){
        desabilitaBotoes();
        chkHabilitado.setSelected(true);
        txtNome.setText(null);
        txtDataNascimento.setDate(null);
        txtDataCadastro.setText(definirDataCadastro());
        txtApelido.setText(null);
        cmbSexo.setSelectedIndex(0);
        txtCPF.setValue(null);
        txtCPF.setBackground(branco);
        txtRG.setText(null);
        txtEmail.setText(null);
        txtTelefoneFixo.setValue(null);
        txtTelefoneCelular.setValue(null);
        cmbEmpresa.setSelectedItem(null);
        cmbCargo.setSelectedItem(null);
        txtUsuario.setText(null);
        txtSenha.setText(null);
        txtSenha2.setText(null);
        txtSenha2.setBackground(branco);
        txtSalario.setText(null);
        txtComissao.setValue((float) 0);
        txtLogradouro.setText(null);
        txtNumero.setText(null);
        txtCEP.setValue(null);
        txtComplemento.setText(null);
        txtBairro.setText(null);
        cmbEstado.setSelectedIndex(25);
        txtObservacoes.setText(null);
    }
    
    private void carregarUsuario(){
        if(usuarioCarregado.getIsHabilitado()==1)
           chkHabilitado.setSelected(true);
        else chkHabilitado.setSelected(false);
        txtNome.setText(usuarioCarregado.getNome());
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        try {
            txtDataNascimento.setDate(dateFormat.parse(usuarioCarregado.getDataNascimento()));
        } catch (ParseException ex) {
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtDataCadastro.setText(usuarioCarregado.getDataCadastro());
        txtApelido.setText(usuarioCarregado.getApelido());
            if(usuarioCarregado.getSexo().equals("M"))
                cmbSexo.setSelectedIndex(0);
            else cmbSexo.setSelectedIndex(1);
        txtCPF.setText(usuarioCarregado.getCpf());
        txtRG.setText(usuarioCarregado.getRg());
        txtEmail.setText(usuarioCarregado.getEmail());
            if(usuarioCarregado.getTelefoneFixo()!=null && !usuarioCarregado.getTelefoneFixo().equals("(  )     -"))
                txtTelefoneFixo.setText(usuarioCarregado.getTelefoneFixo());
            
            if(usuarioCarregado.getTelefoneCelular()!=null && !usuarioCarregado.getTelefoneCelular().equals("(  )      -"))
                txtTelefoneCelular.setText(usuarioCarregado.getTelefoneCelular());
        carregarEmpresa(usuarioCarregado.getEmpresa());
        carregarCargo(usuarioCarregado.getCargo());
        txtUsuario.setText(usuarioCarregado.getLogin());
        txtSenha.setText(usuarioCarregado.getSenha());
        txtSenha2.setText(usuarioCarregado.getSenha());
        txtSalario.setText(String.format("%.2f", usuarioCarregado.getSalario()));
        txtComissao.setValue(usuarioCarregado.getComissao());
        txtLogradouro.setText(usuarioCarregado.getLogradouro());
        txtNumero.setText(usuarioCarregado.getNumero());
        txtCEP.setText(usuarioCarregado.getCep());
        txtComplemento.setText(usuarioCarregado.getComplemento());
        txtBairro.setText(usuarioCarregado.getBairro());
        carregarEstado(usuarioCarregado.getCidade().getEstado());
        carregarCidade(usuarioCarregado.getCidade());
        txtObservacoes.setText(usuarioCarregado.getObservacoes());
        
    }
}
