package model.view;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.bean.Grupo;
import model.bean.Subgrupo;
import model.dao.GrupoDAO;
import model.dao.SubgrupoDAO;
import model.table.GrupoTableModel;
import model.table.SubgrupoTableModel;

public class TelaGrupoSubgrupo extends javax.swing.JDialog {   
    private final GrupoTableModel grupoTableModel = new GrupoTableModel();
    private final SubgrupoTableModel subgrupoTableModel = new SubgrupoTableModel();
    private boolean editando = false;
    
    public TelaGrupoSubgrupo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/images/logoSistema_16px.png")).getImage());
        tblGrupo.setModel(grupoTableModel);
        tblSubgrupo.setModel(subgrupoTableModel);
        carregaGrupo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtRegistrosGrupo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrupo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSubgrupo = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRegistrosSubgrupo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbManipulando = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestão de Grupos e Subgrupos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(246, 91, 92));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grupoSubgrupo_36px.png"))); // NOI18N
        jLabel1.setText("Gestão de Grupos e Subgrupos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel2.setBackground(new java.awt.Color(233, 234, 234));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Grupo:");

        btnNovo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setFocusable(false);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inserir.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setFocusable(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voltar_cancelar.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setFocusable(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setFocusable(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtRegistrosGrupo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtRegistrosGrupo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRegistrosGrupo.setText("NÃO HÁ REGISTROS");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Subgrupo:");

        tblGrupo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGrupoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGrupo);

        tblSubgrupo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblSubgrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblSubgrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSubgrupoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSubgrupo);

        txtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("<html>Nome: <body> <span style=\"color: red;\">*</span></body></html>");

        txtRegistrosSubgrupo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtRegistrosSubgrupo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRegistrosSubgrupo.setText("NÃO HÁ REGISTROS");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("<html>Manipulando: <body> <span style=\"color: red;\">*</span></body></html>");

        cmbManipulando.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbManipulando.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grupo", "Subgrupo" }));
        cmbManipulando.setFocusable(false);
        cmbManipulando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbManipulandoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRegistrosGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbManipulando, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(txtRegistrosSubgrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNome)
                    .addComponent(cmbManipulando))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegistrosGrupo)
                    .addComponent(txtRegistrosSubgrupo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar))
                    .addComponent(btnNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir)
                    .addComponent(btnVoltar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(560, 451));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if((cmbManipulando.getSelectedItem().equals("Grupo") && tblGrupo.getSelectedRow()!=-1) || (cmbManipulando.getSelectedItem().equals("Subgrupo") && tblSubgrupo.getSelectedRow()!=-1)){
            if(((cmbManipulando.getSelectedItem().equals("Grupo") && (((Grupo) grupoTableModel.getRow(tblGrupo.getSelectedRow())).getIdGrupo()!=1)) || ((cmbManipulando.getSelectedItem().equals("Subgrupo") && ((Subgrupo) subgrupoTableModel.getRow(tblSubgrupo.getSelectedRow())).getIdSubgrupo()!=1)))){
                this.editando = true;
                desabilitaBotoes();
            } else JOptionPane.showMessageDialog(null, "Não é possível editar o grupo ou subgrupo Padrão!", "Caixa de Afirmação", 0);
        } else JOptionPane.showMessageDialog(null, "Nenhum registro foi selecionado!", "Caixa de Afirmação", 0);
    }//GEN-LAST:event_btnEditarActionPerformed
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        if(cmbManipulando.getSelectedItem().equals("Subgrupo") && tblGrupo.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null, "Nenhum grupo foi selecionado!", "Caixa de Afirmação", 0);
            cmbManipulando.setSelectedIndex(0);
        } else {
            desabilitaBotoes();
            txtRegistrosGrupo.setText(" ");
            txtRegistrosSubgrupo.setText(" ");
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(cmbManipulando.getSelectedItem().equals("Grupo") && txtNome.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Nenhum grupo foi digitado!", "Caixa de Afirmação", 0);
        else if(cmbManipulando.getSelectedItem().equals("Subgrupo") && txtNome.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Nenhum subgrupo foi digitado!", "Caixa de Afirmação", 0);
        else {
            if(cmbManipulando.getSelectedItem().equals("Grupo")){
                Grupo grupo = new Grupo();
                grupo.setGrupo(txtNome.getText().trim());
                GrupoDAO dao = new GrupoDAO();
                    if(!this.editando){
                        if(dao.adicionaGrupo(grupo)){
                            grupo.setIdGrupo(dao.getLastCodeGrupo());
                            grupoTableModel.addRow(grupo);
                            tblGrupo.setRowSelectionInterval(grupoTableModel.getRowCount()-1, grupoTableModel.getRowCount()-1);
                            subgrupoTableModel.clearRows();
                            habilitaBotoes();
                            controlaTabelas();
                        }
                    } else {
                        grupo.setIdGrupo(((Grupo)this.grupoTableModel.getRow(tblGrupo.getSelectedRow())).getIdGrupo());
                        if(dao.atualizaGrupo(grupo)){
                            carregaGrupo();
                            this.editando = false;
                        }
                    }
            } else if (cmbManipulando.getSelectedItem().equals("Subgrupo")){
                Subgrupo subgrupo = new Subgrupo();
                subgrupo.setSubgrupo(txtNome.getText().trim());
                subgrupo.setGrupo((Grupo) grupoTableModel.getRow(tblGrupo.getSelectedRow()));
                SubgrupoDAO dao = new SubgrupoDAO();
                    if(!this.editando){
                        if(dao.adicionaSubgrupo(subgrupo)){
                            subgrupo.setIdSubgrupo(dao.getLastCodeSubgrupo());
                            subgrupoTableModel.addRow(subgrupo);
                            tblSubgrupo.setRowSelectionInterval(subgrupoTableModel.getRowCount()-1, subgrupoTableModel.getRowCount()-1);
                            habilitaBotoes();
                            controlaTabelas();
                        }
                    } else {
                        subgrupo.setIdSubgrupo(((Subgrupo)this.subgrupoTableModel.getRow(tblSubgrupo.getSelectedRow())).getIdSubgrupo());
                        if(dao.atualizaSubgrupo(subgrupo)){
                            carregaSubgrupo((Grupo) grupoTableModel.getRow(tblGrupo.getSelectedRow()));
                            controlaTabelas();
                            habilitaBotoes();
                            this.editando = false;
                        }
                    }
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if((cmbManipulando.getSelectedItem().equals("Grupo") && tblGrupo.getSelectedRow()!=-1) || (cmbManipulando.getSelectedItem().equals("Subgrupo") && tblSubgrupo.getSelectedRow()!=-1)){
            if(((cmbManipulando.getSelectedItem().equals("Grupo") && (((Grupo) grupoTableModel.getRow(tblGrupo.getSelectedRow())).getIdGrupo()!=1)) || ((cmbManipulando.getSelectedItem().equals("Subgrupo") && ((Subgrupo) subgrupoTableModel.getRow(tblSubgrupo.getSelectedRow())).getIdSubgrupo()!=1)))){
                if(JOptionPane.showConfirmDialog(this, "Você quer mesmo excluir este registro?", "Caixa de Confirmação", 0)==0){
                    if(cmbManipulando.getSelectedItem().equals("Subgrupo")){
                        Subgrupo subgrupo = (Subgrupo) subgrupoTableModel.getRow(tblSubgrupo.getSelectedRow());
                        SubgrupoDAO dao = new SubgrupoDAO();
                            if(dao.removeSubgrupo(subgrupo)){
                                subgrupoTableModel.removeRow(tblSubgrupo.getSelectedRow());
                                if(subgrupoTableModel.getRowCount()>0)
                                    tblSubgrupo.setRowSelectionInterval(0, 0);
                            }
                    } else if (cmbManipulando.getSelectedItem().equals("Grupo")){
                        Grupo grupo = (Grupo) grupoTableModel.getRow(tblGrupo.getSelectedRow());
                        GrupoDAO dao = new GrupoDAO();
                            if(dao.removeGrupo(grupo)){
                                grupoTableModel.removeRow(tblGrupo.getSelectedRow());
                                    if(grupoTableModel.getRowCount()>0)
                                        tblGrupo.setRowSelectionInterval(0, 0);

                            }
                    }
                    exibirInformacoes();
                }
            } else JOptionPane.showMessageDialog(null, "Não é possível excluir o grupo ou subgrupo Padrão!", "Caixa de Afirmação", 0);
        } else JOptionPane.showMessageDialog(null, "Nenhum registro foi selecionado!", "Caixa de Afirmação", 0);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        if(txtNome.isEditable()){
            if(JOptionPane.showConfirmDialog(this, "Você quer mesmo desfazer as alterações deste registro?", "Caixa de Confirmação", 0)==0){
                habilitaBotoes();
                this.editando = false;
                controlaTabelas();
            }
        } else if(JOptionPane.showConfirmDialog(this, "Você quer mesmo voltar à tela anterior?", "Caixa de Confirmação", 0)==0)
                this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void tblGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGrupoMouseClicked
        exibirInformacoes();
    }//GEN-LAST:event_tblGrupoMouseClicked

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        if(!Character.isAlphabetic(evt.getKeyChar()) && !Character.isSpaceChar(evt.getKeyChar()) && !".-&'".contains(evt.getKeyChar()+""))
            evt.consume();
        
        if(txtNome.getText().length()>=15)
            evt.consume();
    }//GEN-LAST:event_txtNomeKeyTyped

    private void tblSubgrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSubgrupoMouseClicked
        exibirInformacoes();
    }//GEN-LAST:event_tblSubgrupoMouseClicked

    private void cmbManipulandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbManipulandoActionPerformed
        controlaTabelas();
    }//GEN-LAST:event_cmbManipulandoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGrupoSubgrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGrupoSubgrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGrupoSubgrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGrupoSubgrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaGrupoSubgrupo dialog = new TelaGrupoSubgrupo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbManipulando;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblGrupo;
    private javax.swing.JTable tblSubgrupo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JLabel txtRegistrosGrupo;
    private javax.swing.JLabel txtRegistrosSubgrupo;
    // End of variables declaration//GEN-END:variables


    private void carregaSubgrupo(Grupo grupo){
        subgrupoTableModel.clearRows();
        SubgrupoDAO dao = new SubgrupoDAO();
            for(Subgrupo subgrupo:dao.getListaGrupo(grupo)){
                subgrupoTableModel.addRow(subgrupo);
            }  
            
            if(subgrupoTableModel.getRowCount()>0)
                tblSubgrupo.setRowSelectionInterval(0, 0);
    }
    
    private void carregaGrupo(){
        boolean first = false;
        grupoTableModel.clearRows();
        GrupoDAO dao = new GrupoDAO();
            for(Grupo grupo:dao.getListaGrupo()){
                grupoTableModel.addRow(grupo);
                    if(!first){
                        carregaSubgrupo(grupo);
                        first = true;
                    }
            }
                if(grupoTableModel.getRowCount()>0)
                    tblGrupo.setRowSelectionInterval(0, 0);
            habilitaBotoes();
            controlaTabelas();
    }

    private void exibirInformacoes (){
        if(cmbManipulando.getSelectedItem().equals("Grupo") && tblGrupo.getSelectedRow()!=-1)
            carregaSubgrupo((Grupo) grupoTableModel.getRow(tblGrupo.getSelectedRow()));
        controlaTabelas();
    }

    private void controlaTabelas(){
        if(cmbManipulando.getSelectedItem().equals("Grupo")){
            tblSubgrupo.setEnabled(false);
            tblGrupo.setEnabled(true);
                if(subgrupoTableModel.getRowCount()>0 && tblSubgrupo.getSelectedRow()==-1)
                    tblSubgrupo.setRowSelectionInterval(0, 0);
                
                if(grupoTableModel.getRowCount()>0 && tblGrupo.getSelectedRow()!=-1){
                    txtNome.setText(((Grupo) grupoTableModel.getRow(tblGrupo.getSelectedRow())).getGrupo());
                    btnExcluir.setEnabled(true);
                } else txtNome.setText(null);
        } else if(cmbManipulando.getSelectedItem().equals("Subgrupo")){
            tblSubgrupo.setEnabled(true);
            tblGrupo.setEnabled(false);
                if(subgrupoTableModel.getRowCount()>0 && tblSubgrupo.getSelectedRow()!=-1){
                    txtNome.setText(((Subgrupo) subgrupoTableModel.getRow(tblSubgrupo.getSelectedRow())).getSubgrupo());
                    btnExcluir.setEnabled(true);
                } else txtNome.setText(null);
        }
        
    if(grupoTableModel.getRowCount()==0 )
        txtRegistrosGrupo.setText("NÃO HÁ REGISTROS");
    else txtRegistrosGrupo.setText("REGISTRO " + (tblGrupo.getSelectedRow()+1) + " DE " + (grupoTableModel.getRowCount()));
    
    if(subgrupoTableModel.getRowCount()==0)
        txtRegistrosSubgrupo.setText("NÃO HÁ REGISTROS");
    else txtRegistrosSubgrupo.setText("REGISTRO " + (tblSubgrupo.getSelectedRow()+1) + " DE " + (subgrupoTableModel.getRowCount()));
}
    
    private void habilitaBotoes (){
        cmbManipulando.setEnabled(true);
        tblGrupo.setEnabled(true);
        tblSubgrupo.setEnabled(true);
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
        txtNome.setEditable(false);
        txtRegistrosGrupo.requestFocus();
    }
    
    private void desabilitaBotoes (){
        cmbManipulando.setEnabled(false);
        tblGrupo.setEnabled(false);
        tblSubgrupo.setEnabled(false);
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtNome.setEditable(true);
            if(!this.editando)
                txtNome.setText(null);
        txtNome.requestFocus();
    }
}
